### ISSUE TITLE
--replace-text is unsafe, while it is safe in BFG

### ISSUE THREAD

**Issue by TobiX** [newren/git-filter-repo#100]
I don't know if this is considered a bug or a feature, but using `--replace-text` on a repository with binary files (for example when replacing CRLF with LF) might damage those files, since the filter is run on every blob.

It appears that BFG is using a simple text file detection and skipped blobs which were not considered text. This difference might surprise users coming from BFG (it surprised me, for example 🤣)

**Comment by newren** [comment]
Oh, interesting.  I made the [lint-history demo](../blob/master/contrib/filter-repo-demos/lint-history) specifically apply to non-binary files only, but for some reason it never occurred to me in the context of `--replace-text`.  I should lift some code from that script and put it in git-filter-repo.

Thanks for the heads up.

**Comment by newren** [comment]
Fixed in commit 31f00a9ff8 (filter-repo: avoid applying --replace-text to binary files, 2020-06-06); thanks for reporting!

**Comment by newren** [comment]
...and this fix is now in the 2.27.1 release.
