### ISSUE TITLE
Question: Is there a way to creating a mapping of old -> new commit SHAs?

### ISSUE THREAD

**Issue by bcanzanella** [newren/git-filter-repo#102]
Similar to the question asked [here](https://stackoverflow.com/questions/14782906/how-do-i-get-a-list-of-old-new-rewritten-commit-shas-from-git-filter-branch) is there a way to create a mapping of old commit SHAs to new commit SHAs?

**Comment by newren** [comment]
It's already created automatically; just look at `.git/filter-repo/commit-map` at the end of the run.  Discussion about documenting this file's format over at #98
