### ISSUE TITLE
Filter on multiple subdirectories?

### ISSUE THREAD

**Issue by tobywstokes** [newren/git-filter-repo#103]
Is it possible to do a multi-subdirectory filter as described here? https://stackoverflow.com/a/17867910

I've tried passing multiple arguments into git filter-repo --invert-paths --path but that does not seem to be supported.

**Comment by newren** [comment]
Doing exactly that is [covered by the second example in the manual](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#EXAMPLES); you simply pass multiple --path arguments, e.g. `--path guides --path tools/releases`

**Comment by tobywstokes** [comment]
Great, thank you for pointing me to that.
