### ISSUE TITLE
Feature Request: Allow comments in --paths-from-file

### ISSUE THREAD

**Issue by Roemer** [newren/git-filter-repo#111]
As the file used in `--paths-from-file` can be quite complex, it could make sense to allow comments in order to comment lines or at least group them.
Best probably would be to ignore all lines that start with a `#`.

**Comment by newren** [comment]
Ooh, I like this idea.  Implemented in commit e75544653e (filter-repo: ignore comment lines in --paths-from-file, 2020-06-20).
