### ISSUE TITLE
Feature Request - remove tags

### ISSUE THREAD

**Issue by amaidment** [newren/git-filter-repo#116]
Please could you add a feature to allow tags to be removed from a git repository?

I understand that the current `--tag-rename` allows one to change the names of tags, but it does not allow one to replace tag names with empty strings (i.e. hopefully to remove them). I tried this (somewhat optimistically) and got the following error:

```
fatal: Branch name doesn't conform to GIT standards: refs/tags/
fast-import: dumping crash report to .git/fast_import_crash_43864
Traceback (most recent call last):
  File "/usr/libexec/git-core/git-filter-repo", line 3933, in <module>
    filter.run()
  File "/usr/libexec/git-core/git-filter-repo", line 3869, in run
    self._parser.run(self._input, self._output)
  File "/usr/libexec/git-core/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/usr/libexec/git-core/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/usr/libexec/git-core/git-filter-repo", line 3426, in _tweak_commit
    self._record_remapping(commit, orig_parents)
  File "/usr/libexec/git-core/git-filter-repo", line 3208, in _record_remapping
    self._output.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

Would it be possible to add a feature, say `--remove-tags` to allow one to do this?
(An alternative would be to change `--rename-tags` such that if it replaced the entire tag name with an empty string it would imply the tag should be removed, but I would suggest that is less clear than a separate command line option.)

If this is already possible using filter-repo (which is awesome, by the way), I'd be delighted to know how to do this.

**Comment by newren** [comment]
Good news: you don't even need a history rewriting tool for this kind of change.  Just run:
```
git tag | xargs git tag -d
```
(You could also do hackier things, like running `git pack-refs --all`, then opening .git/packed-refs in your favorite text editor and removing all lines that have 'refs/tags/' in them.)

If you also have other changes you want to make with filter-repo, you can run the above command either before or after running filter-repo.

**Comment by amaidment** [comment]
Great - many thanks for the swift response.

**Comment by ppena-LiveData** [comment]
If I'm reading [the documentation](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS) correctly, it seems to say that we can use `--tag-callback 'tag.skip()'` to omit all tags, but that doesn't seem to do anything.
