### ISSUE TITLE
Feature Request: Renaming files identified by regex

### ISSUE THREAD

**Issue by amaidment** [newren/git-filter-repo#118]
At the moment, there are 2 [documented ](https://www.mankier.com/1/git-filter-repo#Options-Renaming_based_on_paths_(see_also_--filename-callback))ways of renaming files, --path-rename and --path-rename-match, which I think are the same (?), and match the entire path and filename. 

Would it be possible to find files with a regex, and then substitute that matched part of the path/filename with the replacement text? 

The particular use case I have in mind is to rename files with characters with bad encoding. 
Try as I might, I'm struggling to get these to be renamed using filter-repo --path-rename or --path-rename-match. However, if I could match the bad characters with a regex . (or .+), I would hope to be able to pick them up.

**Comment by newren** [comment]
See --paths-from-file (the entry right after --path-rename in the documentation you link); the examples section includes an example of --path-rename, with one of the lines doing a regex renaming.

**Comment by amaidment** [comment]
Brilliant! Just when I thought filter-repo couldn't be any better, it is! Thanks for the prompt reply.

**Comment by lhunath** [comment]
It's not entirely clear what the syntax of renaming is when combined with operators that apply to multiple paths.

e.g. I can do:
```
mv *.txt doc/
```

But I cannot do:
```
glob:*.txt==>doc/
```

Though it appears that I *can* do:
```
regex:([^/]*\.txt)==>doc/\1
```

This should be documented.  And ideally, the glob should work too.

**Comment by seh** [comment]
Reading [this line of the code](https://github.com/newren/git-filter-repo/blob/fd64b0c7c0c2509ec7399c55128a2651a388b82c/git-filter-repo#L1621) made me think that _git-filter-repo_ might accept an undocumented `--path-rename-regex` flag, but it rejects my attempt to use it.

It would be nice to be able to specify such replacements directly on the command-line, without using an intervening configuration file. I got by with `--filename-callback` instead.
