### ISSUE TITLE
--replace-text add newline

### ISSUE THREAD

**Issue by SampsonCrowley** [newren/git-filter-repo#119]
How can you insert a newline character when replacing text?

e.g. if I wanted to append text after all matches of a specific message

```bash
# replace.txt
my-text-to-replace==>my-text-to-replace\ntext-for-next-line
```

`git filter-repo --replace-text replace.txt`

**Comment by newren** [comment]
You cannot have newlines in the matching or replacing text if you are using the `--replace-text` option.  You'll need to use a --blob-callback instead.
