### ISSUE TITLE
Git repack fails after adding a file and automatic repacking in `filter-repo`

### ISSUE THREAD

**Issue by gabyx** [newren/git-filter-repo#121]
Does anybody have any clue what the problem might be in this question:
https://stackoverflow.com/questions/62539158/why-git-repack-fails-in-filter-repo

Its unfortunate that filter-repo exits with `0` even that re repacking failed.

**Comment by newren** [comment]
Yep, I should check the exit status and handle it; good catch.

A couple other points:
* Your filter-repo script is probably unnecessary; you could use the insert-beginning contrib script as-is.  Adding a new file to the beginning of history will make it appear in all subsquent commits -- unless a file with the same name exists somewhere in history and you are trying to overwrite it with the pristine copy of the file, that is.
* The fact that you get the same error even if you don't use filter-repo suggests the error is outside of filter-repo, as you seem to already be aware.  I'm curious if there are individual files or the combination happens to cross either the 2GB or 4GB boundaries.  It may be that if any level of the OS-stack you are dealing with has 32-bit limitations then you might see weird errors like that, and if the repository is really close to the limit when repacking then it might be hit or miss depending on thread scheduling for how well it packs individual objects.  I've heard that "long" on Windows is still 32-bit even if the OS is 64-bit which might even introduce issues.  I don't know a whole lot in that area myself, but I might be able to dig up some mailing list threads about it.  Anyway, checking the size of your repo (du -hs .git; ls -alrSh .git/objects/pack/), the size of objects in your repo (`git count-objects -v` and the git-sizer program on github may both come in handy), and details about 32-bit vs. 64-bit for each of your Ubuntu image, Virtualbox, and Windows might be useful.
* If you get this outside Virtualbox and learn any more, I'm curious to hear what the answer is or even more details about the problem...though I'll be headed on vacation before too long so I might not respond the quickest.

**Comment by gabyx** [comment]
Thanks for your elaborate answer! This might indeed be really helpful. I am on leave too and will try your recommendations in 3 weeks. I think it definitely might have to do with such a shitty problem. You are right, I probably just add the file at the beginning :). Thx alot!

**Comment by gabyx** [comment]
I will try the whole thing again in native linux.

**Comment by newren** [comment]
Fixed the issue where any of the cleanup commands (not just repack, but also the reflog expiration and the hard reset) fail, so we notice it and report it to the user and exit non-zero.  This was done in 725e478a921b (filter-repo: notice and signal when cleanup commands fail, 2024-08-01).
