### ISSUE TITLE
Question: how to normalize end-of-line

### ISSUE THREAD

**Issue by ymartin59** [newren/git-filter-repo#122]
I am interested in a way to normalize end-of-line to Unix LF in all text blobs for some repositories where `core.autocrlf` has not been set properly or repositories migrated from Subversion where `svn:eol-style` was not properly set.
Is it also possible to insert a `.gitattributes` file in all commits at the same time or in a subsequent invocation?

**Comment by newren** [comment]
The [contrib examples](../blob/main/contrib/filter-repo-demos) may be of interest to you.  Something like this would probably do what you need:

`contrib/filter-repo-demos/lint-history dos2unix`
[edit .gitattributes]
`contrib/filter-repo-demos/insert-beginning .gitattributes`
