### ISSUE TITLE
Question: partial history

### ISSUE THREAD

**Issue by sveneld** [newren/git-filter-repo#126]
I have a very long history in git repository over 300К of commits, with first commit from 2012. Is it possible to make history shorter (from 2016 for example) with git filter-repo?

**Comment by newren** [comment]
Not sure why you'd want to, but yes you can do that.  See the second "Parent rewriting" example from the [examples](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#EXAMPLES) section of the manual.  In that example $commit_A is whatever commit you want to become the new root commit, and $new_parent_or_parents would just be empty.

**Comment by sveneld** [comment]
I wan't remove part of git history. I will try to use your solution
