### ISSUE TITLE
Migrating commit notes to commit messages?

### ISSUE THREAD

**Issue by starseeker** [newren/git-filter-repo#132]
This is really more of a support/doc question than an issue...

I'm faced with a situation where I have a large number of git notes in a repository containing metadata.  The goal is to migrate that data from the notes and add it to the commit messages instead.

Is git-filter-repo able to accomplish a task of this sort?  It's clearly a "rewriting commit messages" task, but it involves not simply altering message data according to a pattern but also needs to extract notes data from each commit as it is preparing to alter the message and then turn around and apply it when doing the msg update.  Is that possible with git-filter-repo?

I apologize if I've missed something in the docs, but I don't see any examples utilizing git-notes data so I'm not quite sure where to start...

**Comment by newren** [comment]
Sorry for the delay in responding.  filter-repo doesn't have much support for notes, based on the fact that fast-export and fast-import don't either.  I've put a little work into fixing that, mostly on the git side, but don't have anything to share yet.

That said, this kind of thing could be done, but it'd involve having the commit filter run some kind of git command to query the repository outside of the information the fast-export is sending in to it -- similar to how the clean-ignore contrib script calls out to `git check-ignore` and the lint-history contrib script calls out to `git cat-file --batch`.

Anyway, I suspect you found some other workaround already or something given that you closed this, but thought I'd follow-up anyway in case others come along and take a look at the issue.

**Comment by starseeker** [comment]
I ended up custom rolling some C++ code combed with calls to git log --pretty:format to extract the note information - not generally useful but seems to have gotten the job done.  Thanks for taking the time to follow up - much appreciated.

**Comment by Krinkle** [comment]
See also https://github.com/newren/git-filter-repo/issues/22

**Comment by lanoxx** [comment]
@starseeker would you be willing to share your C++ code?

I recently asked a question on SO related to this issue (before I had seen this issue):
https://stackoverflow.com/questions/71292587/git-rebase-merge-notes-into-commit-message/71328740?noredirect=1#comment126338191_71328740
