### ISSUE TITLE
Aborting : Refusing to destructively overwrite repo history since

### ISSUE THREAD

**Issue by vyadavmsft** [newren/git-filter-repo#136]
I'm seeing this error on fresh cloned git repo .
 ./git-filter-repo --path arch/arm64/boot/dts/broadcom/stingray/custom/<filename> --path arch/arm64/boot/dts/broadcom/stingray/<filename> --invert-paths
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
  (expected at most one entry in the reflog for HEAD)
Please operate on a fresh clone instead.  If you want to proceed
anyway, use --force.

**Comment by ulmas** [comment]
@vyadavmsft How did you solve this issue? Did you append `--force` or something else?

I tried with `--force`, and it worked, but I get a different error after #156

**Comment by walery** [comment]
To explain the error - the important info in the error message is:

> (expected at most one entry in the reflog for HEAD)

And the important part of the message is

> HEAD

The error appears if you have more than one line in the `.git/logs/HEAD` file (replace HEAD with a string that is in the error message).
The file has more than one line if you have, for example, switched branches after clone.

**Comment by sisrfeng** [comment]
> @vyadavmsft How did you solve this issue? Did you append `--force` or something else?
> 
> I tried with `--force`, and it worked, but I get a different error after #156

I `rm`ed a file in the working tree and `git rm --cache`  fails with "pathspec ... did not match any file" .
I tried `git filter-repo --path /path/to/the/removed_file`, but fails with  "pathspec ... did not match any file"  again.
So I  tried with `--force`, then all the repo's history are gone.

**Comment by rtrad89** [comment]
> To explain the error - the important info in the error message is:
> 
> > (expected at most one entry in the reflog for HEAD)
> 
> And the important part of the message is
> 
> > HEAD
> 
> The error appears if you have more than one line in the `.git/logs/HEAD` file (replace HEAD with a string that is in the error message). The file has more than one line if you have, for example, switched branches after clone.

I have switch to a branch after a clone since the sensitive file is in a branch and not yet on master. It doesn't make sense that I must wait till the file leaks to master, or must I?

**Comment by RamonGiovane** [comment]
> > To explain the error - the important info in the error message is:
> > > (expected at most one entry in the reflog for HEAD)
> > 
> > 
> > And the important part of the message is
> > > HEAD
> > 
> > 
> > The error appears if you have more than one line in the `.git/logs/HEAD` file (replace HEAD with a string that is in the error message). The file has more than one line if you have, for example, switched branches after clone.
> 
> I have switched to a branch after a clone since the sensitive file is in a branch and not yet on `master`. It doesn't make sense that I must wait till the file leaks to `master`, or must I?

I have the same question
