### ISSUE TITLE
"SyntaxError: invalid syntax" after installing 2.28 with PIP on Windows 10

### ISSUE THREAD

**Issue by chriskorosu** [newren/git-filter-repo#144]
C:\Users\cms>pip install git-filter-repo
You are using pip version 6.0.8, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git-filter-repo
  Downloading https://files.pythonhosted.org/packages/c7/a3/f5a470387c6b9c6d560b74d6cee21d56d595c970a439e5e702b595e520a8/git_filter_repo-2.28.0-py2.py3-none-any.whl (97kB)
    100% |################################| 98kB 2.5MB/s
Installing collected packages: git-filter-repo

Successfully installed git-filter-repo-2.28.0

C:\Users\cms>git filter-repo -h
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 3236
    **extra_items}
     ^
SyntaxError: invalid syntax

C:\Users\cms>

**Comment by qwerbzuio** [comment]
I get this very error with python 3.7.9 or python 3.8.5 and git-filter-repo 2.29.0. Output is:
```
$ git filter-repo
  File "C:\Users\bmz3\.local\bin\git-filter-repo", line 3239
    **extra_items}
     ^
SyntaxError: invalid syntax
```

OS is also Windows 10. I installed git-filter-repo via pipx, and the first line of the script looks like this:
```
#!C:\Users\bmz3\.local\pipx\venvs\git-filter-repo\Scripts\python.exe
```
I did check that the mentioned python is the correct version.

Calling `git-filter-repo` directly works. I guess the python version that is called by git (which is 2.7 here) interferes with the one that should be used. I put a `print(sys.executable)` at the beginning of the script (after modifying line 3239 to make it run), which somehow confirms this: output is `C:\Python27\python.exe`.

**Comment by qwerbzuio** [comment]
@newren Shall I open a new issue for my observations above? Or do you want to reopen this issue? Or keep it closed...?
