### ISSUE TITLE
How to delete blobs larger that a certain threshold?

### ISSUE THREAD

**Issue by ldesousa** [newren/git-filter-repo#146]
I am looking for an equivalent command to what is done this way with `bfg`:

```
java -jar bfg.jar --strip-blobs-bigger-than 100M some-big-repo.git
```

I  went through the documentation but could not find something similar. Is it possible to do? 

Thank you.

**Comment by ruv** [comment]
See `--strip-blobs-bigger-than` option in the [documentation](https://github.com/newren/git-filter-repo/blob/main/Documentation/git-filter-repo.txt).

1. Use a fresh clone:
```
git clone --no-local some-big-repo.git ./some-big-repo-new/
```

2. Delete big blobs:
```
git -C ./some-big-repo-new/ filter-repo --strip-blobs-bigger-than 100M
```

**Comment by ldesousa** [comment]
Thank you that is helpful. Is there any way to obtain before hand a list of the objects affected by the `--strip-blobs-bigger-than` flag?

**Comment by ruv** [comment]
See `--dry-run` and `--analyze` options. In the latter case you need `.git/filter-repo/analysis/blob-shas-and-paths.txt` file to inspect. RTFM :)

**Comment by newren** [comment]
@ruv: awesome, thanks for answering.  Much appreciated.  :-)

Looks like that handled all questions so I'll go ahead and close this one out; let me know if I was wrong about that.
