### ISSUE TITLE
No ref-map or commit-map generated

### ISSUE THREAD

**Issue by psv4** [newren/git-filter-repo#150]
Running on Windows with git 2.27.0 and python 3.8, installed with Scoop

Running `git filter-repo` does not produce the commit-map or ref-map files for the git repository.
![image](https://user-images.githubusercontent.com/44118604/91626186-faba0b80-e97a-11ea-9490-a5e244732fdc.png)

**Comment by newren** [comment]
I'm not sure what your picture is meant to show or is showing (do you have a command and directory name blacked-out or something?).  Running `git filter-repo` without any additional arguments is an error so it makes sense that wouldn't generate any files.  You seem to be showing an "analysis" directory, which suggests that you ran "git filter-repo --analyze" which just looks at what is in your repository and doesn't make any changes and thus wouldn't write a commit-map or ref-map file.

Could you list the commands you ran, the results you saw, and how you checked for these files?

**Comment by newren** [comment]
I'll go ahead and close; feel free to re-open with the answers to the above questions, though.
