### ISSUE TITLE
How to modify only a range of commits with instead of the entire branch history?

### ISSUE THREAD

**Issue by cirosantilli** [newren/git-filter-repo#157]
I want to use `git filter-repo` to automatically apply some scripted style-guide refactoring for my multi-commit pull requests.

Therefore I want to apply the operations only to the few latest new commits I'm pushing, but not touch anything else in older history.

Is there a way? Could be either together with existing filters like  `git filter-repo --replace-text`, or requiring a new custom filter.

**Comment by cirosantilli** [comment]
```
git filter-repo --refs HEAD~2..master
```

worked ast mentioned at: https://stackoverflow.com/questions/64154624/how-to-modify-only-a-range-of-commits-with-git-filter-repo-instead-of-the-entire/64155801#64155801

**Comment by synchro--** [comment]
What if i want to specify a filter on specific files?
That command @cirosantilli did not work for me.
