### ISSUE TITLE
git: 'filter-repo' is not a git command

### ISSUE THREAD

**Issue by sandersaares** [newren/git-filter-repo#163]
I followed the install instructions accordingly:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>pip3 install git-filter-repo
Collecting git-filter-repo
  Using cached git_filter_repo-2.28.0-py2.py3-none-any.whl (97 kB)
Installing collected packages: git-filter-repo
Successfully installed git-filter-repo-2.28.0
```

But when I try to run it (e.g. taking the first example command from [user manual](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html)) I get an error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>git filter-repo --analyze
git: 'filter-repo' is not a git command. See 'git --help'.
```

I suspect something may be missing from the documentation. Please advise and/or amend documentation as needed.

**Comment by BobKerns** [comment]
The file has to be on your PATH variable. Locate where pip3 installed it, and add that directory to PATH.
Alternatively, download it manually into a directory of your choosing.
Or use Scoop to install it.

pip3 made it available to be loaded in python, but not git.

For more details, read the installation directions.
https://github.com/newren/git-filter-repo/blob/main/INSTALL.md

**Comment by newren** [comment]
@BobKerns: thanks for jumping in to answer questions; much appreciated!

That's the same answer I'd mention, and we haven't heard further follow-up queries so I'll assume this answer's @sandersaares' question and close it out.

**Comment by sandersaares** [comment]
Nothing in the "installation via pip3" chapter says I need to add anything to the path. I think the instructions need to be updated.

**Comment by newren** [comment]
Installation instructions updated in commit 74ea810872 (INSTALL.md: add notes about common installation issues, 2020-10-19)

**Comment by dzid26** [comment]
The issue for me was that it was installed as User:
```
pip install git-filter-repo  
Defaulting to user installation because normal site-packages is not writeable
```

So I opened Terminal as Admin, and uninstalled and installed again, and now it worked. Because `C:\Program Files\Python313\Scripts` are in the PATH (typically).
