### ISSUE TITLE
Question : Need to reclone after clean ? 

### ISSUE THREAD

**Issue by sebastienroux** [newren/git-filter-repo#166]
Hello,

We are 10 devs on the same repo, if i use filter-repo on it, other devs have to reclone the repo after cleaning ? or it will work just by pulling changes ? 

Thanks.

Sebastien

**Comment by newren** [comment]
This is covered in the ["Discussion" section of the manual](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION); you should read through it.  Short version is that reclone is much safer.
