### ISSUE TITLE
Filtering to keep only relevant history

### ISSUE THREAD

**Issue by kwesolowski** [newren/git-filter-repo#169]
Can the current repo state (i.e. present files and their historical paths) be used as filter?

That would allow to do cleanup in working copy, commit, and scrap all "irrelevant" history.

And if history is not reachable by git (i.e. rename + rewrite in same commit) then its often not really valuable anyway to keep.

**Comment by Codym48** [comment]
I believe [this example](https://github.com/newren/git-filter-repo/blob/75e67bcd44014502cafff67cc8a93d2914f50510/Documentation/git-filter-repo.txt#L781) in the user manual describes how to do what you're trying to do.

**Comment by kwesolowski** [comment]
Thanks. I combined above example with some more python to create "exactly what i needed" (https://github.com/rainlabs-eu/git-relevant-history)
