### ISSUE TITLE
Analysis reports files existing in tags as deleted

### ISSUE THREAD

**Issue by fdevibe** [newren/git-filter-repo#173]
After running `git filter-repo --analyze`, I am, as expected, left with a subdirectory `filter-repo/analysis`, containing files like `path-deleted-sizes.txt`. Now, after examining this file closer, I see there are files listed as deleted that exist in tags. I cannot find this explicitly mentioned in the manual, but I would assume files reported as deleted have either never existed in any given tag or branch, or have been removed from any branch or tag in which it existed. Is this assumption wrong or is this an actual issue?

**Comment by fdevibe** [comment]
In the README file in the analysis directory, the following is said about deletions:

> Whether a file is deleted is not a binary quality, since it can be
> deleted on some branches but still exist in others.  Also, it might
> exist in an old tag, but have been deleted in versions newer than
> that.  More thorough tracking could be done, including looking at
> merge commits where one side of history deleted and the other modified,
> in order to give a more holistic picture of deletions.  However, that
> algorithm would not only be more complex to implement, it'd also be
> quite difficult to present and interpret by users.  Since --analyze
> is just about getting a high-level rough picture of history, it instead
> implements the simplistic rule that is good enough for 98% of cases:
>   A file is marked as deleted if the last commit in the fast-export
>   stream that mentions the file lists it as deleted.
> This makes it dependent on topological ordering, but generally gives
> the "right" answer.

I cannot tell from this whether you can also expect more or less random files being marked as deleted while still being present in various branches or tags. In that case, I would argue that the claim that the results are good enough for 98% of cases is fairly bold, as the user will assume it is safe to remove these files, with fairly unexpected results.

My initial interpretation of this text was, however, that you can get "false positives", in the sense that files could be marked as present even when they are not, but that, it can seem, might not be a correct assumption.

So, is this an actual issue or is this expected behaviour? If it is indeed expected, I think it would be very nice to have a fairly visible warning in the man file and in the headings of the resulting text files stating that the files *may* be deleted or that they are deleted *in the fast-export stream* to avoid misinterpretations.

**Comment by fdevibe** [comment]
I got around this for now by first caching all the files in the leaf nodes, by running `git ls-tree --name-only -r` on all the branches and tags and storing the contents in a dictionary, then going through `path-all-sizes.txt`. If the file exists in the dictionary, I mark it as `present`, otherwise, I mark it as `deleted`.

**Comment by newren** [comment]
Sorry for the long delay in response...

> In the README file in the analysis directory, the following is said about deletions:
> 
> > Whether a file is deleted is not a binary quality, since it can be
> > deleted on some branches but still exist in others.  Also, it might
> > exist in an old tag, but have been deleted in versions newer than
> > that.  More thorough tracking could be done, including looking at
> > merge commits where one side of history deleted and the other modified,
> > in order to give a more holistic picture of deletions.  However, that
> > algorithm would not only be more complex to implement, it'd also be
> > quite difficult to present and interpret by users.  Since --analyze
> > is just about getting a high-level rough picture of history, it instead
> > implements the simplistic rule that is good enough for 98% of cases:
> > A file is marked as deleted if the last commit in the fast-export
> > stream that mentions the file lists it as deleted.
> > This makes it dependent on topological ordering, but generally gives
> > the "right" answer.

Doesn't the "it might exist in an old tag, but have been deleted in versions newer than that" explicitly and directly addressed the exact case you are asking about?  Wording improvements to make that clearer are welcome.

> I cannot tell from this whether you can also expect more or less random files being marked as deleted while still being present in various branches or tags. In that case, I would argue that the claim that the results are good enough for 98% of cases is fairly bold, as the user will assume it is safe to remove these files, with fairly unexpected results.
> 
> My initial interpretation of this text was, however, that you can get "false positives", in the sense that files could be marked as present even when they are not, but that, it can seem, might not be a correct assumption.
> 
> So, is this an actual issue or is this expected behaviour?

Fully expected.  It's not uncommon that people might have (accidentally) checked in really large binaries sometime in the ancient past, and didn't realize their mistake.  Those binaries were tagged with every release.  At some point, someone noticed and deleted the big file(s).  They slowly disappear from all long term maintenance branches and no longer appear in new tags.  Finally, someone gets a chance to delete the old cruft.  These analysis files show that the file is now deleted, and when it was deleted, and the person doing the filtering gets to make the judgement call about whether or not the binaries were even needed in the old versions, and even if they were, whether the old tags pre-dating the deletion date still matter (or, perhaps I should say, whether it matters that the tag that would be checked out after a rewrite exactly matches the tree that you'd get had you checked out the tag before a rewrite).  For some cases, you need a checkout of the tag to provide the same files in the future as it has in the past.  For other cases, you don't.  And that's dependent on your tools, processes, customers, etc.  I've had filtering cases with split rulings on different "deleted" files and whether they needed to be kept or not and for which tags.  But not making any of these visible to any users means they'll have to find another way to find candidate files for cleanup.

The alternative, that you seem to want, is just whether the files were added and removed soon enough to never appear in any tags.  That is perhaps a fine thing to want (though that seems to suggest you think of "deleted" as some type of binary quality, which also goes against the comment you highlighted), but this seems niche enough that it'll provide nearly no helpful information to the majority of users.

From a higher level view, though, it seems you are assuming the analysis reports are designed to be simple crutches that should provide the exact list of things you want to delete.  Does that seem fair?  If so, please realize that what you want is completely impossible.  There's not a chance I'd even attempt to provide something like that.  In more detail...

I expect people who want to do filtering to do their due diligence on what they are removing from history.  I documented the `--analyze` option as creating a report that **_may_** be useful in determining what to filter in a subsequent run.  Anyone who uses it without doing due diligence is either working on a repo of little consequence or is misuing the report.  There are way too many variables involved to write a report that can be relied upon for determining what to filter out of repositories in general.  For all I know, even if some files never appeared in any tags, it might still be important to some customer somewhere that you can check out an old revision and still get exactly the same tree.  That's completely a decision that has to be made locally for each repository being filtered.  But I very much do want to provide something to help users find junk they may want to remove from history in their repo.

One particular experience point for reference: in one particular monorepo, the due diligence I spent on determining which files could be filtered from history took like a week or two after generating the report (and this was a monorepo I was very familiar with and had worked in for years) and involved not only my own spelunking into the history of individual files, but also sending several emails to multiple subject area experts as well.  Without the report that `--analyze` produced, it could have easily doubled that amount of time or more; the list of files that could be deleted that never appeared in any tag would have been empty (or nearly so) and not nearly enough for us to achieve the clone size reductions we were hoping for.

Anyway...does that help?

**Comment by newren** [comment]
I'm going to guess that you resolved your problem or worked around it years ago, and that my response came too late to be helpful.  I'll go ahead and close, but if there are additional questions here, feel free to reopen.  Thanks for filing the ticket, and sorry again for taking so long to respond.

**Comment by fdevibe** [comment]
Thanks for the thorough response and sorry I missed it. At this time, however, I unfortunately can't remember this issue, it created when I was with a past client. From what I can interpret from my old comments, I got around the issue and it seems like you addressed my comments so that if anybody should have similar questions, your response should help.
