### ISSUE TITLE
Files moved with git-filter-repo lose history when moved with git

### ISSUE THREAD

**Issue by milo1892** [newren/git-filter-repo#178]
Heya,

I recently copied a repository to a subdirectory in a monorepo using the method described here:
https://stackoverflow.com/a/62104840/2702627

It seemed to work fine, the history for each file was intact. But when I later tried "git mv" a file to another directory, the file's history disappeared, just the move message was left. Is this a known issue?

Cheers

**Comment by newren** [comment]
What do you mean by the file's history disappeared?  What commands did you run, what output did you see, and what did you expect?  In other words, what led you to this conclusion?

**Comment by milo1892** [comment]
Sorry for the not-so-detailed explanation. I did the following to copy the newly-cloned repo (app) into my newly-cloned monorepo (monorepo):

```
cd ~/projects/app
git filter-repo --to-subdirectory-filter packages/app

cd ~/projects/monorepo
git remote add app ../app
git fetch app
git merge --allow-unrelated-histories app/master
```

I then looked at the history for README.md:

```
❯ git log packages/app/README.md
commit XXX
Author: XXX
Date:   XXX

    docs: Add contribution guidelines to readme

commit XXX
Author: XXX
Date:   XXX

    docs: Add description to readme

commit XXX
Author: XXX
Date:   XXX

    docs: Add readme
```

Looks good! If I then move the README.md file:

```
git mv packages/app/README.md packages/app/README.md.old
git commit -m "Move README"
```

I then look at the history again for the file:

```
❯ git log packages/app/README.md.old
commit XXX
Author: XXX
Date:   XXX

    Move README
```

The three previous commits are now gone, and only the move commit is there.

**Comment by newren** [comment]
So, the issue you are mentioning has nothing to do with git-filter-repo; it's git behavior.  You can see the same thing on a new repo or a repo you've never run git-filter-repo on.  However, there's no bug there either: the meaning of
```
  git log [--] pathname
```
is "Show me the commits that touched this exact pathname", *not* "Show me the commits that touched the content that currently is recorded at pathname".  For the latter, you'd need to add the `--follow` option to git-log.  (As a side note, the `--follow` flag is a bit of a hack, and only works with a single pathname, so if you need to do this with multiple files you unfortunately have to do them one at a time.)

But, the good news is you can add the `--follow` flag if you want to see more history after renaming files.

**Comment by LoyVanBeek** [comment]
I'm seeing the same behavior as @milo1892 . 

I moved some files to a new package in repo A so that I could then move that new package from repo A to repo B. That last bit is not `filter-repo`'s concern of course. 

But I also observe that the history from before the move commit is really gone, also with `git log --follow moved_file.py`

Versions:
- Ubuntu 20.04 
- git version 2.25.1
- `git filter-repo --version`: `e80c1840d9ac`

**Comment by newren** [comment]
@LoyVanBeek: see https://github.com/newren/git-filter-repo/issues/25
