### ISSUE TITLE
`git filter-repo --use-mailmap` in python39 throw the following error 

### ISSUE THREAD

**Issue by pplmx** [newren/git-filter-repo#185]
```bash
$ git filter-repo --use-mailmap
Traceback (most recent call last):
  File "C:\Users\un\AppData\Local\Programs\Python\Python39\Scripts\git-filter-repo", line 3945, in <module>
    args = FilteringOptions.parse_args(sys.argv[1:])
  File "C:\Users\un\AppData\Local\Programs\Python\Python39\Scripts\git-filter-repo", line 2186, in parse_args
    args.mailmap = MailmapInfo(args.mailmap)
  File "C:\Users\un\AppData\Local\Programs\Python\Python39\Scripts\git-filter-repo", line 280, in __init__
    self._parse_file(filename)
  File "C:\Users\un\AppData\Local\Programs\Python\Python39\Scripts\git-filter-repo", line 286, in _parse_file
    raise SystemExit(_("Cannot read %s") % decode(filename))
  File "C:\Users\un\AppData\Local\Programs\Python\Python39\Scripts\git-filter-repo", line 125, in decode
    return bytestr.decode('utf-8', 'backslashreplace')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by newren** [comment]
Just to verify, you don't have a .mailmap file in your current repository root?

Does 'git filter-repo --mailmap .mailmap' work for you?

**Comment by pplmx** [comment]
> Just to verify, you don't have a .mailmap file in your current repository root?
> 
> Does 'git filter-repo --mailmap .mailmap' work for you?

Yep. Without .mailmap file in the current repo root, but a mailmap in my $HOME.
I can use like this `git filter-repo --mailmap ~/my_mailmap`

**Comment by newren** [comment]
I've got a proposed fix up on the use-mailmap-fix branch.  Could you try it out for me?  It works locally for me, but I don't have a windows box to test on (and GitHub Actions has been flaky recently), and I'm curious whether Windows is okay with bytestrings vs. strings in some of the subsequent portions of the code.  I have a vague memory of it not being happy with bytestrings as filenames.

**Comment by pplmx** [comment]
Hello, @newren

Still error
```
Unparseable mailmap file: line #1 is bad: b'Mystic new@cc.com old@cc.com\n'

```

**Comment by newren** [comment]
Cool, glad that works for you for this issue.

We're tracking the submodule issue separately, so I'll leave that one open.
