### ISSUE TITLE
Question about IDE on Windows

### ISSUE THREAD

**Issue by cvbge** [newren/git-filter-repo#2]
Hello, 

I'm trying to edit the script on Windows. Tried VS Code and PyCharm. Both have problems with recognizing git-filter-repo import in splice_repos.py - either they don't find the file, or they don't recognize members like fr.Blob

Any idea why?

**Comment by newren** [comment]
The filter-repo repository has a symlink to git-filter-repo named git_filter_repo.py, specifically for the python import issue.  However, this symlink needs to be in your $PYTHONPATH (or, if symlinks aren't supported on your version of Windows, then make a copy of git-filter-repo named git_filter_repo.py and stick it somewhere in your $PYTHONPATH).  I'll fix up the docs to mention this.

**Comment by cvbge** [comment]
Thanks. It's working now. I tried it before, and it didn't work. Must have made some mistake.
