### ISSUE TITLE
Add installation instructions via scoop on Windows

### ISSUE THREAD

**Issue by kostrse** [newren/git-filter-repo#20]
On Windows this tool can be easily installed via the [Scoop](https://github.com/lukesampson/scoop) package manager:
```
scoop install git-filter-repo
```

Here is the manifest:
https://github.com/ScoopInstaller/Main/blob/master/bucket/git-filter-repo.json

Could you consider adding it to your installation instructions?

**Comment by newren** [comment]
There are dozens and dozens of package managers out there, so I'm hesitant to track every one of them.  Luckily, it appears that there is a site, repology.org, that is willing to track that, and provide links for any project out there.  So, I updated the install instructions to mention package managers in general, mentioned scoop as an example for Windows, and linked to repology.org's auto-updating image showing which package managers have packaged it (scoop is apparently one of three to do so thus far).
