### ISSUE TITLE
[question] How to determine how many commits in a branch?

### ISSUE THREAD

**Issue by gmikhaile** [newren/git-filter-repo#221]
What I'm trying is to check whether a branch contains only one commit. I suppose it is possible to do with `ancestry_graph` but I'm not sure how.

**Comment by newren** [comment]
`git rev-list --count $branch` ?  I'm not sure how this is related to filter-repo, though...

**Comment by gmikhaile** [comment]
> `git rev-list --count $branch` ? I'm not sure how this is related to filter-repo, though...

When I migrated from SVN to git there are empty commits which were SVN tags. When I filtering my repo I want to convert empty commits to normal git tags.

I think I know how to determine if a commit was a SVN tag `ancestry_graph` is the key.

**Comment by newren** [comment]
Ah, trying to clean up from migrations.  You may also want to take a look at https://gitlab.com/esr/reposurgeon; it was specifically designed around migrating between different version control systems, and knows about a lot of weird special cases in how CVS, svn, and others represent history unusually and has ways of making it more canonical.  I haven't used it myself, but Eric's ported some pretty big repos over to git with it.

Also, from the extra context, I'm guessing you wanted to know whether a branch only contains one *unique* commit; every commit references it's parent, thus when you create a new branch it contains every commit up to the point of its creation automatically.  If you add just one commit to that branch, then it contains N+1 commits, where N is the number contained in whatever starting point you provided.  Anyway, you can get a list of commits in a branch that aren't found in some other branch like so: `git rev-list --count $BRANCH ^$EXCLUSION_BRANCH`, e.g. `git rev-list --count my-fun-feature-branch ^master`.

**Comment by gmikhaile** [comment]
Thank you, this will help A LOT.
