### ISSUE TITLE
Binary-blob detection is broken in filter-repo-demos/lint-history with Python3

### ISSUE THREAD

**Issue by thebrandre** [newren/git-filter-repo#223]
The detection of binary blobs in `lint_non_binary_blobs` is broken in Python3. It will currently normalize all blobs, binary and text alike, due to a type mismatch.

Here is a small demo of the underlying issue:
```python
any(x==b'1' for x in b"123")
# returns True in Python2 and False in Python3 because different types are returned on iteration:
[type(x) for x in b"123"]
# Python2: [<type 'str'>, <type 'str'>, <type 'str'>]
# Python3: [<class 'int'>, <class 'int'>, <class 'int'>]
```
My solution would be based on:
```python
b'1' in b"123"
# returns True in Python2 and Python3
b'4' in b"123"
# returns False in Python2 and Python3
```

This means that in cobtrib/filter-repo-demos/lint-history
```python
def lint_non_binary_blobs(blob, metadata):
  if not any(x == b"0" for x in blob.data[0:8192]):
    filename = '.git/info/tmpfile'
```
should in actually check for
```python
if not any(x == 0 for x in blob.data[0:8192]):  # Python3 only!
```
or even better (faster and works in both Python2 and Python3)
```python
if b"\0"not in blob.data[0:8192]:
```

**Comment by newren** [comment]
Awesome!  Thanks so much for tracking this down and providing such a clear report, and with the fix to boot!

I fixed this in commit 6985cd3076 (lint-history: fix binary blob detection, 2021-03-29), crediting you in the commit message with the fix.  Thanks so much!
