### ISSUE TITLE
is it possible to include and exclude in one command?

### ISSUE THREAD

**Issue by nikita-skobov** [newren/git-filter-repo#230]
Sometimes I want to include a folder, but exclude a file within the folder. consider:

```
src/file1.c
src/file2.c
src/lib1/lib1.c
src/README.md
docs/doc1.txt
```

And I might want to do:

```sh
# to include src/
git filter-repo --path src/
# to exclude README.md:
git filter-repo --invert-paths --path src/README.md
```

Is it possible to do the above in one command?

**Comment by newren** [comment]
Use the `--filename-callback` option when you need greater versatility on the rules for inclusion, exclusion, and even renaming. 
 For example,

```
git filter-repo --filename-callback 'return filename if (filename.startswith(b"src/") and not filename == b"src/README.md") else None'
```

If you want to expand that across multiple lines for readability, you can, which might make it easier to see how to extend it even further:
```
git filter-repo --filename-callback '
    if filename == b"src/README.md":
        return None
    if filename.startswith(b"src/"):
        return filename
    return None'
```
