### ISSUE TITLE
Question: how to reliably compare dry-run and original .git/filter-repo/fast-export ?

### ISSUE THREAD

**Issue by gberche-orange** [newren/git-filter-repo#237]
### Expected behavior

As a filter-repo user, in order to check effects that my expressions will have, I need to review a diff of the filter-repo dry-run actions.

### Observed behavior

When running [--dry-run option](https://github.com/newren/git-filter-repo/blob/75e67bcd44014502cafff67cc8a93d2914f50510/Documentation/git-filter-repo.txt#L328-L333
) and then diffing the output with the following command

```
diff --text --ignore-matching-lines='original-oid' .git/filter-repo/fast-export.original .git/filter-repo/fast-export.filtered
```

Then I see some differences in line feeds around `from :` blocks that make the diff output unreliable, e.g.

```diff
< initial commit, based on spring boot starter (spring integration)from :4
---
> initial commit, based on spring boot starter (spring integration)
> from :4
```

I'm reproducing this against this version:

```
$ git filter-repo --version
10401e45d5f0
$ git version 
2.31.1
```

**Comment by newren** [comment]
Yeah, unfortunately, the fast-import stream format is somewhat loose and allows extra newlines in various places.  fast-export may or may not add extra newlines in those places where it is allowed.  filter-repo does the same, and to be used in this way, it'd have to record exactly what extra newlines appeared and output exactly in that format.

However, I think you could change your strategy just slightly in a way that should work:
  * First, run without any special options other than --dry-run: `git filter-repo --dry-run`
  * Make a backup of the result: `cp .git/filter-repo/fast-export.filtered .git/filter-repo/fast-export.no-op-filtered`
  * Then run with the real options along with --dry-run: `git filter-repo --dry-run $other_options ...`
  * Diff the two filtered versions: `diff --text --ignore-matching-lines=original-oid .git/filter-repo/fast-export.no-op-filtered .git/filter-repo/fast-export.filtered`

Does that make sense?

**Comment by gberche-orange** [comment]
thanks @newren for looking into this issue. Apparently, the output of the 1st command `git filter-repo --dry-run` does not output the content of the files into `.git/filter-repo/fast-export.filtered` , whereas the 2nd one (with `--replace-text replace.txt` option in my case) does (even when no modifications are actually brought to the files).

Hence this break the diff, with the right part showing full content of the repo files

Is there an option I missed to have a consistent behavior

**Comment by newren** [comment]
Ah, yes, filter-repo tries to avoid filtering blobs if it doesn't need to.  Try adding `--blob-callback="pass"` to the first dry-run, which will force it to process the blobs but leave them all unchanged.

**Comment by gberche-orange** [comment]
@newren, the `--blob-callback="pass"` hint was useful, and the procedure you suggested is matching my needs, thanks !

**Comment by newren** [comment]
Awesome, glad it helped!
