### ISSUE TITLE
"fatal: this operation must be run in a work tree" error message when running bfg-ish

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [newren/git-filter-repo#240]
This error message is printed whenever I run `bfg-ish` (no matter what the working directory is, including in the GIT_WORK_TREE).

```command-output
$ LANG=C PYTHONPATH="${PWD}" ./contrib/filter-repo-demos/bfg-ish --replace-text replace.txt test/.git
Processed 3 blob sizes
Parsed 1 commits
New history written in 0.01 seconds...
fatal: this operation must be run in a work tree
Completely finished after 0.02 seconds.
Repacking your repo and cleaning out old unneeded objects
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
```

The error message doesn't seem to be critical though, but I still like to eliminate it whenever possible.

**Comment by newren** [comment]
I fixed this with commit dc012d277b0c (bfg-ish: add some sanity checks on the specified repo, 2021-06-05), which would make the code abort with an error message pointing out the user's error in this case:

`For non-bare repos, please specify the toplevel directory (test) for repo`
