### ISSUE TITLE
subdirectory filtering seems to drop some history

### ISSUE THREAD

**Issue by AlexeyRaga** [newren/git-filter-repo#244]
Looks like when a file is moved into a subfolder, and then this subfolder is extracted using `git filter-repo --path <subfolder>` then any history prior to the time when the file was moved into the subfolder is missing from the log.

Is it a limitation or a bug or I need to do it differently?

**Comment by newren** [comment]
History following isn't a thing that exists; when the manual says that --path is for "**Exact** paths (files or directories) to include in filtered history.", it really means *exact* paths.  See https://github.com/newren/git-filter-repo/issues/25#issuecomment-559919385 for more details.

I know this isn't what you wanted to hear, but that other comment explains how you can use --analyze to figure out potential renames and include them in the commands you specify to filter repo.
