### ISSUE TITLE
Setup.py throws on windows unless running as administrator

### ISSUE THREAD

**Issue by CervEdin** [newren/git-filter-repo#249]
This isn't exactly a severe issue but running `setup.py` on windows throws unless running as an administrator since creating a symlink on Windows requires administrator privileges'.

Possible solutions:

- Add documenation to run as administrator
- Change the symlink to hardlink on Windows

Not sure exactly sure what the symlink is for, so I'm not sure what the best fix is.

Thanks for an awesome script, I love it.

**Comment by newren** [comment]
I'm glad you are enjoying the script.

setup.py exists solely for uploading git-filter-repo to PyPI, which only someone doing releases should run.  Someone else contributed it (and I have to admit I don't really understand all the setup and pypi stuff).  I presume copies would work as well as symlinks.

Out of curiosity, what are you trying to use setup.py for?  It's not referenced in the installation documentation anywhere.

**Comment by CervEdin** [comment]
Actually I think I just assumed this was the reason the install failed when running a non-elevated shell. I believe I was using scoop.

**Comment by newren** [comment]
setup.py was removed in 2c9cc90609a7 (Modernize and simplify Python packaging, 2023-09-24), making this obsolete.  I suspect scoop has long since fixed up their installation bug, but if not, someone can file an issue with them.
