### ISSUE TITLE
**extra_items syntax error

### ISSUE THREAD

**Issue by gitpository** [newren/git-filter-repo#253]
Hi,

First time using on Windows (after renaming python3 to python), got this error:

```
git filter-repo

  File "C:\Users\gitpository\AppData\Roaming\Composer\vendor\bin\git-filter-repo", line 3239
    **extra_items}
     ^
SyntaxError: invalid syntax
```
-- signed
Not a python guy

PS
```
$ python

Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32 
```

**Comment by newren** [comment]
I suspect you closed because you discovered the issue, but just in case someone else comes across this bug report, the error above means the version of python in use is too old.  If you don't have python3 >= 3.5, then it'll throw this kind of SyntaxError.
