### ISSUE TITLE
running git filter-repo spawns a separate python shell

### ISSUE THREAD

**Issue by CervEdin** [newren/git-filter-repo#256]
I've already installed on two other machines without much hassle. I installed `git-filter-repo` using scoop on a new machine but this time, whenever I run `git filter-repo` it's spawning in a separate Python shell in a new window. Maybe not so much a `git-filter-repo` but more a python/scoop/environment issue. Maybe other's have some insights or there are other people who'll run into the issue in the future.

It's the same version, same shebang.

```
$ which git-filter-repo
~/scoop/shims/git-filter-repo
```

No issues running the python script

```python3
#!/usr/bin/env python3

print("foo")
```

If I run `/usr/bin/env` I don't see anything odd in the PATH or environment variables.

No problem running `~/scoop/apps/git-filter-repo/2.29.0/git-filter-repo` directly but running `~/scoop/shims/git-filter-repo` launches a python shell on the new machine not the others.

I've solved it by adding `~/scoop/apps` before `~/scoop/shims/` in my path but that doesn't seem correct

**Comment by newren** [comment]
No clue.  Are ` ~/scoop/apps/git-filter-repo/2.29.0/git-filter-repo` and `~/scoop/shims/git-filter-repo` the same?  Which one, if either, looks like the copy from this repo?  (Does the latter do some weird stuff and then call the real filter-repo?  If so, maybe ask the Scoop folks about it since the only git-filter-repo I provided is the one from this repo?)

**Comment by CervEdin** [comment]
`~/scoop/shims/git-filter-repo` is a shell script that looks like it's invoking a PS script

```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted "~\scoop\apps\git-filter-repo\current\git-filter-repo.ps1"  "$@"
```

which is

```
﻿if (!(Test-Path Variable:PSScriptRoot)) { $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent }
$path = join-path "$psscriptroot" "..\apps\git-filter-repo\current\git-filter-repo.ps1"
if($myinvocation.expectingInput) { $input | & $path  @args } else { & $path  @args }
```

which invokes

```
python3 '~\scoop\apps\git-filter-repo\2.29.0\git-filter-repo' @args
```

That script is identical to `git-filter-repo@v2.29.0`

**Comment by newren** [comment]
So is powershell mucking with $PATH, such that `python3` in the final step you mention now refers to a different python3 than what would have been executed had you directly run `~\scoop\apps\git-filter-repo\2.29.0\git-filter-repo` ?

That's my only guess here, but regardless, none of the scripts you mention above are things that I wrote (I don't even know powershell), so perhaps ask the scoop folks what might be going on?

**Comment by newren** [comment]
I'll go ahead and close out, since this doesn't look like a filter-repo thing and hopefully the tip to ask the scoop folks helped you get what you needed.

**Comment by CervEdin** [comment]
Reasonable. I solved it by adding the shims to the path, besides I don't use that environment anymore. I mainly reported the issue to document if others faced the same issue
