### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by cschuber** [newren/git-filter-repo#259]
Is it possible to move the documentation or just the man page to the main branch instead of docs. Those who use the github API to download release tarballs (i.e. FreeBSD ports), there is no clean way to build and install (create a package) without a git clone within build infrastructure (not ideal).

BTW, I crudely cobbled a FreeBSD port. (Ports result in binary packages when poudriere gets around to building it a few days later.)

**Comment by newren** [comment]
I'm sorry this is a headache for you, but I'm not wiling to check generate build results into the main branch.  The main branch stores the source code, including the sources for the documentation.  The docs branch is just a convenience for those who aren't using release tarballs and who don't want to attempt to wrangle asciidoc/asciidoctor/etc.

I'm curious, though, what about the github API gives you something different than when I download the release tarballs?  The release tarballs are meant to contain the generated documentation alongside the sources.  See e.g. git-filter-repo-2.32.0/Documentation/html/git-filter-repo.html and git-filter-repo-2.32.0/Documentation/man1/git-filter-repo.1 from the 2.32 release tarball.

**Comment by newren** [comment]
No answer to my question in the second paragraph, so I'll the release tarballs do indeed provide what you need.  Shout if that turns out to be a bad assumption.

Thanks for packaging filter-repo in FreeBSD!
