### ISSUE TITLE
Installation via brew installs new python

### ISSUE THREAD

**Issue by geekykant** [newren/git-filter-repo#266]
Installing git-filter-repo on macos, the command provided `brew install git-filter-repo` installs the latest python (3.9), without checking the existing system's python version > 3.5.

My System Specification - Python (3.8.1)

### Steps to produce
- Have any python version on MacOS system
- Run `brew install git-filter-repo`

![Screenshot 2021-07-14 at 12 39 43 PM](https://user-images.githubusercontent.com/27401142/125579389-76b050bf-55f0-449d-89ea-3a732c33c181.png)

**Comment by newren** [comment]
I don't control the brew packages; if the brew packaging is bringing in unnecessary dependencies, you'll need to report it to them.
