### ISSUE TITLE
git update-index --chmod=-x path/to/file

### ISSUE THREAD

**Issue by galeksandrp** [newren/git-filter-repo#268]
`Git` stores executable bit for files. Is there any way to unset executable bit over all history?

Why: `WSL2`, popular `Linux` on `Windows` solution, mounts `Windows` directories with executable bit over all files. That makes sense, because files on `NTFS` don't have executable bit, and yet they may be needed to be executed in `Linux`.

In regular work, I setuped `core.filemode=false` option, and yet I discovered that some commits are contains executable bit over all files, causing hude senseless diffs.

**Comment by newren** [comment]
You'd need to use the commit callback, and modify the file modes.  Note that git uses the modes 100644 (normal file), 100755 (executable), 120000 (symlink), or 160000 (submodule).

Assuming you have no symlinks or submodules, and want to change the mode of all files whose extension is not ".sh"), it'd look something like this:

```
git filter-repo --commit-callback '
  for change in commit.file_changes:
    if not change.filename.endswith(b".sh"):
      change.mode = b"100644"
  '
```

If you just wanted to make all files not be executable, you could get rid of the 'if' condition.  If there are symlinks or submodules, you'd want to extend the if-check to exclude those.  But this should get you started.

**Comment by galeksandrp** [comment]
Done with
```
git-filter-repo --commit-callback 'for change in commit.file_changes:
  if change.mode == b"100755":
    change.mode = b"100644"'
```
thanks!
