### ISSUE TITLE
Allow to pass values to callbacks

### ISSUE THREAD

**Issue by nkiesel** [newren/git-filter-repo#270]
Hi,

I need to replace text in commit messages (updating ticket ids).  The actual ids vary.  Right now, the only way I see how to do this is
to use shell string interpolation which makes this pretty messy (e.g. have to use `"` and then watch for other `$` usages in the callback body).

This would be much easier if I could do
```
git filter-repo -b v1 'old value' -b v2 'new value' --message-callback '
  return re.sub(f"\\b{v1}\\b".encode(), v2.encode(), message)
'
```

**Comment by nkiesel** [comment]
I found a  workaround:
```
v1='old value'
v2 = 'new value'
git filter-repo  --message-callback "
v1 = '${v1}'
v2 = '${v2}'
"'
  return re.sub(f"\\b{v1}\\b".encode(), v2.encode(), message)
'

**Comment by nkiesel** [comment]
BTW: is there a description about what modules are pre-imported for the callbacks? `re` is obviously one of them, but are there more?

**Comment by newren** [comment]
> I found a workaround:
> 
> ```
> v1='old value'
> v2 = 'new value'
> git filter-repo  --message-callback "
> v1 = '${v1}'
> v2 = '${v2}'
> "'
>   return re.sub(f"\\b{v1}\\b".encode(), v2.encode(), message)
> '
> ```

Yeah, if it's just constants it makes a lot more sense to just handle yourself; there's no need to change filter-repo.  Good job!

**Comment by newren** [comment]
> BTW: is there a description about what modules are pre-imported for the callbacks? `re` is obviously one of them, but are there more?

Yeah, good point.  Basically, it's this:
```
$ grep ^import git-filter-repo
import argparse
import collections
import fnmatch
import gettext
import io
import os
import platform
import re
import shutil
import subprocess
import sys
import time
import textwrap
```

**Comment by newren** [comment]
I think you answered your own original question, and I gave an answer to the BTW above, so I'll go ahead and close out.  Sorry for the delay, and thanks for your interest!
