### ISSUE TITLE
analyze is slow/stuck in big repo

### ISSUE THREAD

**Issue by sluongng** [newren/git-filter-repo#271]
Hi,

I started test out filter-repo on a repo with >1.5M commits and its stuck/became very slow after 14 hours of running:

```
[sluongngoc@centos-7-machine]/path/to/big-repo% git filter-repo --analyze
Processed 13256689 blob sizes
Processed 1345980 commits
```

After checking with `ps auxf`, it seems like git diff-tree call here is fairly expensive and is still running on a single thread
```
sluongn+ 18744  0.0  0.0 120400  1416 pts/1    S+   Jul30   0:00      \_ /usr/bin/git filter-repo --analyze
sluongn+ 18745  0.4 13.0 2263064 2121200 pts/1 S+   Jul30   3:34          \_ /usr/bin/python3 /home/sluongngoc/.local/bin/git-filter-repo --analyze
sluongn+ 20081  0.0  0.0 113288  1344 pts/1    S+   Jul30   0:00              \_ /bin/sh -c git rev-list --topo-order --reverse --all | git diff-tree --stdin --always --root --format=%H%n%P%n%cd --date=short -M -t -c --raw --combined-all-paths
sluongn+ 20082  0.0  4.5 2371624 747360 pts/1  S+   Jul30   0:20                  \_ git rev-list --topo-order --reverse --all
sluongn+ 20083 99.6 21.6 10733052 3522368 pts/1 R+  Jul30 851:56                  \_ git diff-tree --stdin --always --root --format=%H%n%P%n%cd --date=short -M -t -c --raw --combined-all-paths
```

I am using `git version 2.31.0.293.g2e70200971` which was build on https://github.com/git/git/commit/576ba9dcdaf1007243f5a5cb4bf1a1e7b8fcf850 with a patch adding our internal CI on top (no other modification)

```
% git filter-repo --version
3c2f87e20b4f
```

**Comment by newren** [comment]
Yes, I run
```
git rev-list --topo-order --reverse --all | git diff-tree --stdin --always --root --format=%H%n%P%n%cd --date=short -M -t -c --raw --combined-all-paths
```
and parse the output as part of --analyze.  That does take a while to run, but 14 hours and slow/stuck seems excessive.

What's the output of `git count-objects -v` in this repository?  What is your `diff.renameLimit` set to?  How many files in a typical commit in this repo?  Were there ancient commits with massive numbers of renames in this repo?  It is appears that it is not just 2e70200971 which is not part of git.git; the other commit you link to (git/git @ 576ba9d) also does not exist in that repository.  In fact, following the link says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."  Could you retry with a released version of git?  And while at it, what does the memory usage look like on this machine?

If you run the command from the command line what's the final commits it shows before getting slow/stuck?

**Comment by sluongng** [comment]
It's finished running after I left it over the weekend. Here is some stats

```
% wc -l <renames.txt
150426
```

Here is the config value you asked for
```
% git config -l | grep rename
diff.renamelimit=4096 #system config
diff.renamelimit=999999 #user config
```

I must have increased it in an experimental attempt of converting the repo to Mercurial and forgot about it.

Here is the stats (I rounded it to avoid providing exact number)
```
% git count-objects -v
count: 0
size: 0
in-pack: 13300000
packs: 4
size-pack: 6500000
prune-packable: 0
garbage: 0
size-garbage: 0
```

> Were there ancient commits with massive numbers of renames in this repo?

Yes, ancient and recent. We have many root tree level renaming/refactoring over the years.

> the other commit you link to (git/git @ 576ba9d) also does not exist in that repository

I think it was HEAD of `next` at one point?
But I don't think it's relevant right now, our git version is fairly recent which is the point.

---

I will try to lower the renameLimit to see if next run is faster. Thanks for the pointer!

**Comment by newren** [comment]
> ```
> % git config -l | grep rename
> diff.renamelimit=4096 #system config
> diff.renamelimit=999999 #user config
> ```
> 
> I must have increased it in an experimental attempt of converting the repo to Mercurial and forgot about it.
...
> > Were there ancient commits with massive numbers of renames in this repo?
> 
> Yes, ancient and recent. We have many root tree level renaming/refactoring over the years.

I believe the behavior is pretty well described by these above two bits of info, and there's probably not much to be gained by continuing to leave this open.  Anyway, I'm glad it finished for you when you left it running for a weekend and seem to have a handle on things now.  Let me know if there's anything else that comes up.
