### ISSUE TITLE
How to get GIT_AUTHOR_NAME and EMAIL in --message-callback

### ISSUE THREAD

**Issue by kuvaldini** [newren/git-filter-repo#272]
This code is from example

           git-filter-repo --message-callback '
             if b"Signed-off-by:" not in message:
               message += b"\nSigned-off-by: Me My <self@and.eye>"
             return re.sub(b"[Ee]-?[Mm][Aa][Ii][Ll]", b"email", message)'

I'd like to modify it to sign-of with git-commit-autor which is not constant, as following

           git-filter-repo --message-callback '
             signature=f"Signed-off-by: {author.name} <{author.email}>".encode('utf-8')
             if signature not in message:
               message += signature
             return message

How to obtain git commit author name and email in callback function?

**Comment by newren** [comment]
If you want author name and email, don't use `--message-callback`; use `--commit-callback`.  As noted in the documentation, the commit callback passes a commit which has, among other things, an author_name, author_email, and message field, so you'd just have the commit callback update commit.message using commit.author_name and commit.author_email.
