### ISSUE TITLE
Removing subtrees?

### ISSUE THREAD

**Issue by tjohnston-cd** [newren/git-filter-repo#28]
Can this tool be used to remove subtrees? I want to remove their files and all related commits, so that it's as if I had never added subtrees to my repo.

When I created my subtrees, I did not use the `--squash` option. 

My commit history right now looks like this (newest to oldest):
- Commits to this git repo (outside the subtrees)
- Group of subtree merge commits (created by `git subtree add`)
- Initial commit to this git repo
- Many earlier commits which came from the subtreed repositories

When I try to run `git-filter-repo --invert-paths --path path/to/subtree --path path/to/othersubtree ...`, the files are removed but not the commits. I've experimented with using the `--replace-refs`, `--prune-empty` and `--prune-degenerate` flags, but nothing has worked so far. On the plus side, each run is _much_ faster than when I was trying to use `git filter-branch` for this!

Any ideas? Am I just missing something simple?

**Comment by newren** [comment]
filter-repo by default only removes commits if they become empty; are there other changes that were made as part of those commits that are outside the paths you are removing?  You may want to run `git log --name-status ...` to get a look at some of the commits in question and see which files they still modify.  (I'll assume for now that we're not dealing with commits that started empty.)  Of course, if you have a complex enough series of merges, then merge commits may need to be retained just to preserve the commit topology.  So `git log --graph --name-status ...` might be handy.

It's hard to say more without getting a chance to look at the repo in question, but hopefully that helps you narrow it down.

**Comment by tjohnston-cd** [comment]
Ah, interesting.. your reply got me thinking, and I see what's happening now.

After I `git-filter-repo` the path containing my subtree, **the merge commit** for that is rewritten (so it no longer creates files in the subtree path). The child commits for that subtree are still in the repo (and they're not empty, so they're not being removed).

So..I need to make all the subtree history's commits empty as part of this.

**Comment by newren** [comment]
Glad you understand; I'll go ahead and close out.
