### ISSUE TITLE
Clarify installation instructions

### ISSUE THREAD

**Issue by amandapouget** [newren/git-filter-repo#286]
```git-filter-repo is a single-file python script, which was done to make installation for basic use trivial: just copy it into your $PATH.```

What is `it` in this sentence? Clone the repo?

**Comment by clcaldwell** [comment]
Incase you are still waiting for an answer on this, is to just copy the file named _git-filter-repo_ into your $PATH (this file: https://github.com/newren/git-filter-repo/blob/main/git-filter-repo ). Whether you do this by cloning the whole repo and then copying just that file over to $PATH, copying it directly into $PATH via cURL, or even just copy and paste the contents into a new file named _git-filter-repo_ in $PATH is up to you.

**Comment by CS-Cowboy** [comment]
The CORRECT way to do this in Window 10 is add a NEW ENTRY in your environment variables pointing to where your git-filter-repo folder is.

**Comment by newren** [comment]
Thanks @clcaldwell, for explaining.  I committed 240ef0bcc262 (README.md: clarify simple instruction rules and antecedent of `it`, 2021-11-09) to try to clear this up.
