### ISSUE TITLE
Question: Will we eventually have this built-in to git?

### ISSUE THREAD

**Issue by DillFrescott** [newren/git-filter-repo#289]
This is an amazing tool!

**Comment by wenfangdu** [comment]
@DillFrescott Hello, which OS are you on?

**Comment by DillFrescott** [comment]
@wenfangdu can I ask why you are asking this?

**Comment by wenfangdu** [comment]
@DillFrescott I'm on Windows, and this tool is [not working](https://github.com/newren/git-filter-repo/issues/288) for me at all.

**Comment by DillFrescott** [comment]
@wenfangdu Do you have the newest python installed and on your path?

**Comment by DillFrescott** [comment]
@wenfangdu I put the git-filter-repo.put file on my main path and then I just type 'git-filter-repo.py [command)'

I never added it to git or anything it's completely by itself on my path and just does it's thing on the repos when I give it a command.

**Comment by wenfangdu** [comment]
@DillFrescott Thanks for your help, [TTT](https://stackoverflow.com/users/184546) and I co-authored [some solutions](https://stackoverflow.com/a/69356543/7881859) for this.

**Comment by newren** [comment]
@DillFrescott: I'm glad you enjoy it.  :-)

To answer the question, I did propose it on the git mailing list for inclusion.  The discussion instead took the path of expunging things from git.git -- particularly filter-branch, but also all the foreign scm tools (git-svn, git-p4, etc.), and various other things (git-subtree, git-gui, git-daemon, gitweb, maybe gitk).  Things could change, but the current weight of opinion seems to be more on the side of making git itself only include very core things, and having a diverse field of other useful tools.

Anyway, hope that helps.

**Comment by DillFrescott** [comment]
@newren Got it! Thanks for the info!
