### ISSUE TITLE
I don't understand what `--replace-refs` does and how its options affect it

### ISSUE THREAD

**Issue by akharrou** [newren/git-filter-repo#295]
Hello, I've read the documentation and tried to experiment with `--replace-refs` but I still don't understand what it does and how it's possible options (`delete-*`, `update-*`) affect it.

**Comment by newren** [comment]
Documentation of these options was rewritten in 0f1c9d8ddd4b (filter-repo: change the --replace-refs default to 'update-no-add', 2024-07-17), which should hopefully make it a bit easier to understand.  Further, the default was changed to `delete-no-add` in 85d0e9916674 (filter-repo: change the --replace-refs default to 'delete-no-add', 2024-07-29) which means that users will usually not have any replace refs to deal with, making users less likely to wonder what the refs are and how to use them.  I hope between these two that answers any questions, but if not, feel free to reopen.
