### ISSUE TITLE
filter-repo does not automatically follow renames, much like other git commands do not

### ISSUE THREAD

**Issue by Sergio0694** [newren/git-filter-repo#297]
Hello, we're currently in the process of migrating the .NET projects from the [Windows Community Toolkit](https://github.com/CommunityToolkit/WindowsCommunityToolkit) into a separate repository, and I'm trying to do so while preserving history. I found this tool as it was recommended by git when trying to use `filter-branch` (following some guides I had found), but I can't get either to work the way I'd like to. Here's what I have tried:

- Cloned https://github.com/CommunityToolkit/WindowsCommunityToolkit into a new folder
- Created a new `dotnet` branch
- Moved all the folders/projects to keep into a temporary "nct" folder, so they'd all be in one place.
  - I did make sure to use `git mv` when moving things, so history would correctly be preserved for all files.
- Install `git-filter-repo`
- Run `git filter-repo --path nct/`

This results in **all** commits being lost (??), with just the last two remaining, **but** incorrectly rewritten.
By that I mean they just show all files in that folder as being newly added, with all history being lost:

![image](https://user-images.githubusercontent.com/10199417/138855479-cff2d147-692c-4a14-bfc8-9f97f2f93b14.png)

I suspect this might be due to the fact that those files are now in a different folder than the one they were originally added in, so the tool is somehow incorrectly tracking them when going through the history? I do want to preserve history including past file moves for all the files that are currently in this "nct" folder though. Is there a way to do this with this tool?

Thanks! 😄

**Comment by newren** [comment]
You need to specify all the paths you want to preserve.  e.g. --path nct --path oldfolder/component --path otherfolder/sub/directory.  (Yes, you can pass multiple --path arguments.)  If you're worried you don't know all the relevant paths, first run with the --analyze option and look at the generated renames.txt file for hints; it doesn't handle copies and renames uses git's heuristics which may not be valid if e.g. you had multiple similar files and the most-similar-file was not the actually correct one to pair up with.

If you'd like to modify the history to make it appear that the files always appeared under nct/, then you can also use the --path-rename option to make it rewrite it.

Make sense?

**Comment by newren** [comment]
Since this seems to come up a lot, I made a change to the documentation to make this much more explicit; see commit 933475ecf1b5 (Make it clearer that --path* do not follow renames, 2021-11-09)
