### ISSUE TITLE
SyntaxError: invalid syntax in git-filter-repo in line 3146  **extra items}

### ISSUE THREAD

**Issue by sukritkapil27** [newren/git-filter-repo#30]
Hi newren,
I am getting the following error when trying to execute the command **$ git filter-repo** 
![Python error](https://user-images.githubusercontent.com/58801895/70687816-3b330580-1cd6-11ea-90e9-0a7ced80fbc8.jpg)

I have Python33 installed on my office system. Also, I am new to git and as well as python(installed it for the very first time) so apologies from my side if this a trivial issue.

Thanks in advance

**Comment by newren** [comment]
Hi,

As stated in the README, python >= 3.5 is required; you'll need to upgrade your python version.

Hope that helps,
Elijah

**Comment by sukritkapil27** [comment]
> Hi,
> 
> As stated in the README, python >= 3.5 is required; you'll need to upgrade your python version.
> 
> Hope that helps,
> Elijah

Works perfectly.
Thanks!!

**Comment by GigiSan** [comment]
Just to add to the cases, if you have the mandatory need to keep **multiple versions** of Python on your **Windows machine**, you can add the path to the exe manually to the **first line** of **git-filter-repo**.

Turn:
`#!/usr/bin/env python3`

Into:
`#!/usr/bin/env <path_leading_to>\python.exe`

Example on my PC:
`#!/usr/bin/env C:\Users\myuser\AppData\Local\Programs\Python\Python38-32\python.exe`
