### ISSUE TITLE
Please allow to pass user_data to the callbacks

### ISSUE THREAD

**Issue by cryptomilk** [newren/git-filter-repo#31]
Hi,

I'm trying to write a tool to add "Reviewed-By" to commits. It would be great to have user_data which I could pass down to the commit_callback.

Thanks!

**Comment by newren** [comment]
Just in case anyone is searching through issues and doesn't want to click through to the PR in the future, there are two ways of passing user_data to callbacks already:

* People can create a class and a function within a class, and then use everything in self for extra callback data (see e.g. contrib/filter-repo-demos/filter-ignore, which passes commit_callback=checker.skip_ignores)
* Even if people don't want to create a full class, they can always use functools.partial (https://docs.python.org/3/library/functools.html#functools.partial) to bind one or more user callback data arguments to some function with additional parameters to make it match the necessary call signature.

**Comment by cryptomilk** [comment]
Thanks!

Here is my script: https://git.cryptomilk.org/users/asn/dotfiles.git/tree/git/bin/git-review+
