### ISSUE TITLE
Hangs my entire Windows PC

### ISSUE THREAD

**Issue by jdx-john** [newren/git-filter-repo#312]
I'm brand new to filter-repo and it looks great, but trying to use it at all in a Windows console _totally_ hangs the machine. Like to the extent TaskManager stops working properly and I have non-responsive console I cannot force close... haven't had to forcibly reboot my PC for ages!

I have Python 3.7 (IIRC) installed which is run as "py" - not python or python3 - and edited the top of the file accordingly.
I can see python runs up but even if I add `dry-run` or `debug` options I get no output. In fact if I just run `git filter-repo` with no arguments at all it still hangs.

Is this a python issue or some other know issue - it feels like it is not even getting properly started? I'm on a modern Windows 10 box, I don't know where `py` has come from as I don't use Python - it must be installed by some part of our development toolchain I am not familiar with. 

If I can provide more useful information, let me know? Thanks in advance for any help.

**Comment by merrickclay** [comment]
I had the same problem with Python 3.9 installed (also ran as "py"). I'm not sure what exactly fixed the problem for me, but I will list the steps I went through here:

1. Get a fresh copy of your repo (ex. clone it to your device from github if you previously tried git-filter-repo on it)
2. Uninstall Python 3.9 and Python Launcher (if on your device)
3. Install Python 3.10 from Microsoft Store
4. Check to make sure the command 'python3' works
5. Download git-filter-repo and git-filter-repo.py file
6. Put them in your 'git --exec-path' directory
7. Run 'git filter-repo' in command prompt (with no arguments). If you get a response that says "No arguments specified." then your problem has most likely been solved.
8. Navigate to your repo and try to use the tool normally.

Let me know if this has helped you. It took me a forced reboot and a lot of trial and error to get it to work.

**Comment by jdx-john** [comment]
So I tried running `python3` and it launched the Windows app store... apparently this is normal. I let it install (3.9 I think) and changed the script back to `python3` rather than `py`. Things now seem to work... thanks for your input.
