### ISSUE TITLE
error after moving subdirectory to root

### ISSUE THREAD

**Issue by rafalkrupinski** [newren/git-filter-repo#32]
I'm trying to pull a subdirectory of a repo to a separate repo with all the files directly in the repo root.
So...

```
% git-filter-repo --path modules/openapi-generator/src/main/resources/python --path-rename modules/openapi-generator/src/main/resources/python:.`
Parsed 13471 commits
New history written in 8.65 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
error: invalid path './README.mustache'
fatal: Could not reset index file to revision 'HEAD'.
```

Looks like it's a problem when moving a contents of a subdirectory to repo-root as it works with
```
% git-filter-repo --path modules/openapi-generator/src/main/resources/python --path-rename modules/openapi-generator/src/main/resources/python:root
Parsed 13471 commits
New history written in 6.59 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Updating files: 100% (24796/24796), done.
HEAD is now at 96473f9305 [Python] Remove mutable default argument (#4665)
Enumerating objects: 434, done.
Counting objects: 100% (434/434), done.
Delta compression using up to 4 threads
Compressing objects: 100% (172/172), done.
Writing objects: 100% (434/434), done.
Total 434 (delta 209), reused 392 (delta 182)
Completely finished after 9.71 seconds.
```

**Comment by newren** [comment]
Thanks for the report.  I can add some checks to make it error out if people specify the invalid paths '.', '..', or maybe even '.git'.  Since --path-rename is just a string replacement (with a bit of help for handling the trailing slash for you) and since git records paths by their relative path (meaning it'll never record a name like './README'), you shouldn't be trying to rename 'modules/openapi-generator/src/main/resources/python' to '.' but to '' (the empty string).  This should work for you:

`git filter-repo --path modules/openapi-generator/src/main/resources/python --path-rename modules/openapi-generator/src/main/resources/python:`

where there is nothing after the colon character.

**Comment by rafalkrupinski** [comment]
Thank you very much for the explanation. Yes, a specific error message would have been very helpful :)

Cheers

**Comment by newren** [comment]
I added an error message for this case to the code; thanks for the report!

**Comment by jcrites** [comment]
I also ran into this error trying to move a subdirectory to root. The proposed solution of using an empty string to represent the project root seems to cause an error: "fatal: Empty path component found in input".

Is this use-case currently supported? (Or am I mistakenly using an old version? I am using version 81cc263d7659 according to `--version`)

```
% ~/git-filter-repo/git-filter-repo --path lib/react-app/src --path-rename lib/react-app/src: --force
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_2930
Traceback (most recent call last):
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3913, in <module>
    filter.run()
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3850, in run
    self._parser.run(self._input, self._output)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3406, in _tweak_commit
    self._insert_into_stream(commit)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3825, in _insert_into_stream
    self._parser.insert(obj)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1392, in insert
    obj.dump(self._output)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 720, in dump
    change.dump(file_)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 621, in dump
    file_.write(b'M %s %s %s\n' % (self.mode, self.blob_id, quoted_filename))
BrokenPipeError: [Errno 32] Broken pipe
```

```
 % ~/git-filter-repo/git-filter-repo --version
81cc263d7659
```

**Comment by newren** [comment]
The last comment is not quite the same as the original bug report; it'll be handled in the separate new bug report and this one can remain closed.
