### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by Victordongy** [newren/git-filter-repo#323]
Hi wondering whether it supports Ubuntu 18.04 installation ? Since it shows `unable to locate package git-filter-repo` after using `sudo apt-get install`

**Comment by robert-skarzycki** [comment]
I have the same issue with Ubuntu 20.04 LTS version (WSL2). :/

**Comment by Victordongy** [comment]
您好感谢您的来件，本人将及时阅览，谢谢。
北京大学国家发展研究院

VICTOR DONG

**Comment by ePaul** [comment]
Hi, Ubuntu usually doesn't add new packages to older versions of the distribution, and I guess they've decided to only add it for later versions. This is something decided by the Ubuntu maintainers, not each package's author.

You can still install the script manually following any of the other instructions, it will work if your python and Git are new enough.

**Comment by Victordongy** [comment]
您好感谢您的来件，本人将及时阅览，谢谢。
北京大学国家发展研究院

VICTOR DONG

**Comment by newren** [comment]
Thanks again for answer, @ePaul!  Yeah, I was kind of surprised that Ubuntu was a laggard in picking up git-filter-repo; lots of other linux distribution picked it up and distributed before they did.  git-filter-repo works just fine on older Ubuntu versions, but it's their choice whether to include it in one of their packages.  Anyway, I'll close this out.

**Comment by Victordongy** [comment]
您好感谢您的来件，本人将及时阅览，谢谢。
北京大学国家发展研究院

VICTOR DONG
