### ISSUE TITLE
Project readme describing installation process is very, very unclear and highly frustrating

### ISSUE THREAD

**Issue by Keavon** [newren/git-filter-repo#328]
I struggled to install this, so here's a look at my thought process as I go through it. Hopefully you can improve the user experience of installing the software.

I am looking at the main readme and it tells me that it's a simple Python script, just place it in the $PATH. Ok, easy enough. Hmm, where do I get this script? The readme doesn't link it. Maybe I go to GitHub's releases section. Ok, I can download it as a `.tar.xz` file, whatever that is, or the source code. I don't want the source code since it sounds like you distribute a version that get compiled into a single standalone `.py` file which I'm looking for. So perhaps that `.py` file is compressed in the `.tar.xz` file? Might as well download it and give that a try. Oh, Windows has no default file association for `.xz` files? What the heck even is that format and why do some people insist on using these exotic archive/compression formats? What's wrong with a simple `.zip` that everyone can recognize and open without special software? Alright, I'll find where it downloaded, right click, and open it in 7-Zip. Weird, there are a whole bunch of files in here, basically the entire source repository. I wanted to just download the script, not the source code, that's why I didn't click the "Source code (zip)" button on the GitHub release page. Well, I do see `git_filter_repo.py` in the 7-Zip interface so I'll drag that to my desktop. Umm, an error from Z-Zip saying "Can not create symbolic link : A required privilege is not held by the client." Well I have never seen an error extracting a file from Z-Zip before, and frankly this is getting very frustrating. I literally just want to download a text file, how hard can you make this be? Ok, perhaps I have to extract the entire archive instead of dragging out an entire file. Let's stick this archive in a new folder and right click > 7-Zip > Extract Here. Ok, now I have a `.tar` file, I suppose that's expected. I'll delete the `.tar.xz` and Extract Here again with the `.tar`. Wow, seriously? That failed also, I get that same error showing up twice. Although it did still extract everything into a folder. Let's go grab the Python file I'm after: oh hey, it's 0 kilobytes, the file is empty. How helpful. Ok, I'm giving up on that and maybe I can grab just this Python file directly from the GitHub file listing. Wait, what is this "folder with an arrow" icon in the GitHub file list? I guess it might be a symlink or something? I'll click it I suppose. I was thinking it might bring me to some other file which has the actual Python script I'm looking for, but it actually just shows the contents, a single line of text that says `git-filter-repo`. Another dead end. Let's explore more of the repo file structure. I see a folder called "release", I wonder what's in there. A Python script called `setup.py` and also `setup.cfg`. The former only has 21 lines of code, and I'm a little hesitant to try that, since the readme just said I need a simple Python script to stick in my $PATH, it didn't say anything about setup. Another dead end. This is seriously frustrating now. Back to the installation section of the readme. Even though that section of the readme said "See INSTALL.md for things beyond basic usage or special cases." and I don't need anything beyond the basic use case, I will click on that because I'm out of other ideas here. Ok, this readme starts out with "Installation via Package Manager". Unless it supports a package manager like npm or pip, I don't have one with my OS since I'm on Windows. Scroll down, "Notes for Windows Users", ok, let's read this. It's telling me some warnings about problems with a Python installation. I checked by typing `python` into my console, I assume I've installed it at some point in the past, it says I'm using `Python 3.9.2`. Hopefully this is the "real" python, not the "fake" python that ships with Windows according to this warning I just read. It also says I might need to modify the Python executable path on the first line of the git-filter-repo script. Ok, but WHERE IS THE SCRIPT!? Next up is the "Manual Installation" section of this markdown document. It tells me about several important files in the repo, I would rather not have to read all this but maybe one of them is the script I'm trying to find. So the `git-filter-repo` file is apparently the script I'm looking for, and the `.py` version is (as I eventually came to suspect) a symlink? WHY!?!?!?!?!?! I will try extracting the version of the script without the file extension from that exotic archive file and renaming it to end in `.py`, since I assume I can't just run it directly (I'll have to prefix it with `python` when I call it). Ok, `python git-filter-repo`. And it gives me back `No arguments specified.`, yay, finally! Holy crap, that was like pulling teeth.

I typed that out as I went to offer some insights into my mental processes while trying to install the software. A lot of it involved serious frustration. My goal with filing this issue isn't to convey anger or hatred, but it's to help explain what your users are having to go through every time they try to install your software. The friendly little "we made this into a standalone Python script so it's nice and easy for you to run anywhere" set me up for expecting something easy, but that instantly betrayed my trust enough to make me open up an issue and type out the rest of my process. This felt user-hostile, the same kind of user-hostile attitude I am tired and fed up with from open source projects that don't provide binaries and expect users to download the source and spend the next 18 hours getting cmake to build their code. Luckily I didn't actually have to compile my own binaries, but the exotic file extension instead of `.zip`, the symlink, the python file that's not a python file, the not-python file that's a python file, the lack of links to useful downloads or files, the GitHub releases page not just having the script, and the description in the readme that oversimplifies a fundamentally non-trivial problem and provides no hints without digging into the details in other links, all of these were very frustrating. It feels like the readme is written with good intentions, but clearly has never had consideration taken for what an actual user has to go through in an average case. Please take my bad experiences as lessons for improvement in many areas that failed me today.

Now that I have the script running, I look forward to trying it out. Thank you for making it.

**Comment by newren** [comment]
[I updated the INSTALL.md file](https://github.com/newren/git-filter-repo/blob/main/INSTALL.md#simple-installation) to point out that people just need to download the `git-filter-repo` file, and then just run `python3 git-filter-repo ...`.
