### ISSUE TITLE
Using --analyze shows error message

### ISSUE THREAD

**Issue by bradykelly** [newren/git-filter-repo#338]
I have just installed git-filter-repo via Scoop, and installed the .html help file. The command `git filter-repo --help` works fine and opens the man page in my browser. 

The command `git filter-repo --analyze` does not work and returns the following error text:
`Traceback (most recent call last):
  File "C:\Users\Brady.Kelly\scoop\apps\git-filter-repo\current\git_filter_repo.py", line 1, in <module>
    git-filter-repo
NameError: name 'git' is not defined`

My python is 3.10 and runs with the command `python3`. I don't know what other info you need from me.

**Comment by bradykelly** [comment]
I solved this by just copying git-filter-repo into the git exec path

**Comment by fawazahmed0** [comment]
Thanks, that helped, I copied the `git-filter-repo` file to the folder where `git.exe` existed

**Comment by fawazahmed0** [comment]
You could also do this:
```
sudo wget https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -P `git --exec-path`
```
