### ISSUE TITLE
How to exclude unrelated commit tags when extracting part of the repository

### ISSUE THREAD

**Issue by Mdkhan1518** [newren/git-filter-repo#341]
### Discussed in https://github.com/newren/git-filter-repo/discussions/200

<div type='discussions-op-text'>

<sup>Originally posted by **Rgzevs** February  4, 2021</sup>
I've inherited a repository that contains several unrelated projects and am trying to split it using `git-filter-repo`. 
My problem is that while filtering repository by folder the output  contains tags from the commits that didn't affect the selected folder. For example the repository contains folders A and B and the commits look like this:

1. Files in folder A, tag:<1>
2. Files in  folder B, tag:<2>
3. Files in folder B, tag:<3>
4. Files in folder A, tag:<4>

So if I want to filter only commits from folder A, I'm expecting the resulting commits to be like this:

1. Files in folder A, tag:**<1>**
4. Files in folder A, tag:**<4>**

But when I run  `git-filter-repo --subdirectory-filter A --replace-refs delete-no-add ` instead the result looks like this:

1. Files in folder A, tag:**<1>**
4. Files in folder A, tags:**<4>,<2>,<3>**

So it looks like all tags from the commits that have been filtered out are added to the next commit that fits the filter.
Is it possible to drop all the unrelated tags from `git-filter-repo` output?

</div>

**Comment by Mdkhan1518** [comment]
steamkar id,573918761

**Comment by newren** [comment]
Stupid spam accounts.  See #335, #336, #337, #340 and perhaps others.  The real question here was just copy & paste from discussion #200; someone else's question.
