### ISSUE TITLE
Improve lint-history script

### ISSUE THREAD

**Issue by camlafit** [newren/git-filter-repo#345]
Hello

I've some improvement to propose about this script
* Restore **--force** argument, as filter-repo destroy (purge, ...) could be useful to record user to have a backup previous to run this script
* Enable filter-repo arguments, at least looks useful to enable **--refs** argument. Maybe could be to add others arguments related to filter content.

**--force** et and **--refs** optons looks easy, I could propose a patch. About arguments generalization I've no idea how to propose a great approach without duplicate all argument from git-filter-repo.

Thanks

**Comment by newren** [comment]
--refs was added by commit 3e153806ff47 (lint-history: Add --refs argument, 2021-12-30)...and fixed in commit 9cf6121b34fe (lint-history: fix broken --refs option, 2022-10-03).  So that one at least is already taken care of.

**Comment by newren** [comment]
I have left the lint-history script in the repository, but it becomes somewhat useless after the new --file-info-callback added in commit 615720731589 (filter-repo: add a --file-info-callback, 2024-10-23).  That adds a callback which allows you to work with both the filename and file contents (and file mode), which can handle everything lint-history was doing and a bunch more.
