### ISSUE TITLE
git filter-repo doesn't push releases

### ISSUE THREAD

**Issue by SAURABH110894** [newren/git-filter-repo#350]
Hi Team, 

I have followed this docs https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html#purge-files-from-repository-history. 

I couldn't found how to push releases from one repo to another. 

Example :- 

git push origin --force 'refs/heads/*' --> We can push all branches 
git push origin --force 'refs/tags/*' --> We can push all tags 

what about releases file ?

Can you please help me ?

**Comment by ePaul** [comment]
"Releases" is not a Git term, it's something Gitlab (as well as Github and other hosting platforms) add on top. (I'm not sure whether it's even part of the repository.)
So I'd suggest to ask Gitlab support.

**Comment by newren** [comment]
Thanks for the comments @ePaul.  I have to agree; in GitHub at least, releases are not metadata that are part of the repository, but something on top.  I suspect the same is true in GitLab.  Not being part of the repository, they aren't something you can push and pull.  So I'll have to echo @ePaul's comments here and suggest asking GitLab if you need to mirror/modify/update releases somehow.
