### ISSUE TITLE
Should a misstyped directory create an empty folder?

### ISSUE THREAD

**Issue by lagamura** [newren/git-filter-repo#361]
Enviroment:
---------------
Windows 11 Machine
GitBash terminal
---------------

Replication:
My purpose is to create a new repository from a subdirectory, so i typed in GitBash: 
`git filter-repo --subdirectory-filter SUBDIRECTORY\SUB-SUBDIRECTORY`

So, i confused because of windows '\' with '/' which should be used in gitbash.
I've got as an output -without any warning - an empty folder, which should be considered a bug.

This is my first usage of filter-repo, so sorry if i missed something in the way of thinking.

**Comment by newren** [comment]
Pre-searching every path provided through all of history to see if some commit contains it, and then throwing a warning or error if none is found, would be a very expensive pre-run-time check; one I've been unwilling to impose.  Perhaps using `git filter-repo --analyze` and looking at the output to see which paths are present would be helpful?

There are many other ways to mess up a rewrite as well; I can't generally check them all.  When they are also expensive to check, I tend to think it's better to let users check if the results are to their liking, which thanks to having a fresh clone means that if the answer is no they can just toss the clone and redo it.

Sorry if that's not the answer you wanted, but I'm not sure what could reasonably be done here.

**Comment by lagamura** [comment]
@newren Thanks a lot for your answer, your description is very detailed and instructive for a junior like me.
