### ISSUE TITLE
[feature request] Add git-lfs import migration support

### ISSUE THREAD

**Issue by rconde01** [newren/git-filter-repo#378]
In comparison to git-filter-repo, git-lfs migration is VERY slow. It occurred to me that the processes should be very similar, so whatever techniques you use for great performance in git-filter-repo would also be applicable to git-lfs migration. Thus would be very nice if you could add this capability.

**Comment by rconde01** [comment]
I see there are some starting points here:
https://github.com/newren/git-filter-repo/issues/7#issuecomment-929967079

**Comment by newren** [comment]
Yeah, since we already have #7 open, I'm going to close this issue as a duplicate.
