### ISSUE TITLE
Error when renaming author 

### ISSUE THREAD

**Issue by u9wy** [newren/git-filter-repo#380]
I'm getting the following error when trying to execute an author rename in a bash script.

`Traceback (most recent call last):
  File "/home/u9wy/.local/bin/git-filter-repo", line 8, in <module>
    sys.exit(main())
  File "/home/u9wy/.local/lib/python3.9/site-packages/git_filter_repo.py", line 4000, in main
    filter = RepoFilter(args)
  File "/home/u9wy/.local/lib/python3.9/site-packages/git_filter_repo.py", line 2760, in __init__
    self._handle_arg_callbacks()
  File "/home/u9wy/.local/lib/python3.9/site-packages/git_filter_repo.py", line 2865, in _handle_arg_callbacks
    handle('commit')
  File "/home/u9wy/.local/lib/python3.9/site-packages/git_filter_repo.py", line 2858, in handle
    setattr(self, callback_field, make_callback(type, code_string))
  File "/home/u9wy/.local/lib/python3.9/site-packages/git_filter_repo.py", line 2840, in make_callback
    exec('def callback({}, _do_not_use_this_var = None):\n'.format(argname)+
  File "<string>", line 3
    if commit.author_email == btest@email.com
                                                                          ^
SyntaxError: invalid syntax`

I'm running the following command:

`git filter-repo --commit-callback '
    if commit.author_email == b'"$(getAuthorEmail)"':
        commit.author_email = b'"$newAuthorEmail"'
        commit.author_name = b'"$newAuthorName"'
        commit.committer_email = b'"$newAuthorEmail"'
        commit.committer_name = b'"$newAuthorName"'
'`

It seems to have something to do with the variables because when I replace it with the following it works without an issue.

`git filter-repo --commit-callback '
    if commit.author_email == b"incorrect@email":
        commit.author_email = b"correct@email" 
        commit.author_name = b"Correct Name"
        commit.committer_email = b"correct@email" 
        commit.committer_name = b"Correct Name"
' `

Can someone see anything wrong with what i'm trying to do?

**Comment by newren** [comment]
This really isn't a filter-repo question but a shell question.  To see that, try running this:
```
echo ' foo '"bar"' baz '
```
If you do, you'll notice that it outputs
```
 foo bar baz
```
NOT
```
 foo "bar" baz
```
If you want the latter, you'd need to do something like
```
echo ' foo "'"bar"'" baz '
```

Basically, your quotes are being eaten up by the shell, If you replace `git filter-repo --commit-callback` with `echo`, you'll see exactly what is being passed to filter-repo.  Make sure it looks correct first.

Hope that helps.
