### ISSUE TITLE
SyntaxError: bytes can only contain ASCII literal characters

### ISSUE THREAD

**Issue by mratmartinez** [newren/git-filter-repo#383]
Many people from Spanish-speaking countries have names or surnames that use what's called an [acute accent](https://en.wikipedia.org/wiki/Acute_accent). These are not supported by the bytes type:

```
>>> b'Martínez'
  File "<stdin>", line 1
    b'Martínez'
          ^
SyntaxError: bytes can only contain ASCII literal characters
```

This means that if you try to change the author of a commit using git-filter-repo it will fail:

````
$ git filter-repo --commit-callback '
    if commit.author_email == b"example@test.com":
        commit.author_name = b"Fernández"
        commit.committer_name = b"González"
' 
Traceback (most recent call last):
  File "/usr/libexec/git-core/git-filter-repo", line 4004, in <module>
    main()
  File "/usr/libexec/git-core/git-filter-repo", line 4000, in main
    filter = RepoFilter(args)
  File "/usr/libexec/git-core/git-filter-repo", line 2760, in __init__
    self._handle_arg_callbacks()
  File "/usr/libexec/git-core/git-filter-repo", line 2865, in _handle_arg_callbacks
    handle('commit')
  File "/usr/libexec/git-core/git-filter-repo", line 2858, in handle
    setattr(self, callback_field, make_callback(type, code_string))
  File "/usr/libexec/git-core/git-filter-repo", line 2840, in make_callback
    exec('def callback({}, _do_not_use_this_var = None):\n'.format(argname)+
  File "<string>", line 4
    commit.author_name = b"Fernández"
                               ^
SyntaxError: bytes can only contain ASCII literal characters
````

Is it possible to avoid using bytes for this kind of operation?

**Comment by mratmartinez** [comment]
Well, I just read this in the [Contributing.md](https://github.com/newren/git-filter-repo/blob/main/Documentation/Contributing.md) file. So I guess, it won't be possible, @newren?

> In filter-repo, it's not just OK to use bytestrings, you are expected to use them a lot. Using unicode strings result in lots of ugly errors since input comes from filesystem names, commit messages, file contents, etc., none of which are guaranteed to be unicode. (Plus unicode strings require lots of effort to verify, encode, and decode -- slowing the filtering process down). I tried to work with unicode strings more broadly in the code base multiple times; but it's just a bad idea to use an abstraction that doesn't fit the data.

**Comment by newren** [comment]
> Many people from Spanish-speaking countries have names or surnames that use what's called an [acute accent](https://en.wikipedia.org/wiki/Acute_accent). These are not supported by the bytes type:

No, you've misunderstood the error; all names are representable as bytes.  In contrast, some sequences of bytes stored on disk may not be valid UTF-8 strings and thus a string type is insufficient for handling names, commit messages, and filenames. 
 I had to use something more general that could hold whatever had been written to disk.  That's where the bytes type comes in; it can handle anything.

You just need to convert your strings to bytes (and all strings can be).  In this case:
```
    commit.author_name = "Fernández".encode()
    commit.committer_name = b"González".encode()
```

Sure, you can't use the `b"MyName"` convenient shorthand (a python restriction), but it's not too much harder to get the data you need.
