### ISSUE TITLE
git-filter-repo:944: DeprecationWarning: invalid escape sequence '\d'

### ISSUE THREAD

**Issue by 2-5** [newren/git-filter-repo#385]
I have warnings turned on for my Python (they are turned off by default), and it's warning on this line when I run `git filter-repo`:

```bash
H:\Git>git filter-repo
H:\Console\git-filter-repo:944: DeprecationWarning: invalid escape sequence '\d'
  parent_regex_rules = (b' :(\d+)\n$', b' ([0-9a-f]{40})\n')
No arguments specified.
```

https://github.com/newren/git-filter-repo/blob/main/git-filter-repo#L944

Python recommends marking regular expressions literals with `r''` (raw string):

```python
parent_regex_rules = (br' :(\d+)\n$', br' ([0-9a-f]{40})\n')
```

https://docs.python.org/3/library/re.html:

> Also, please note that any invalid escape sequences in Python’s usage of the backslash in string literals now generate a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) and in the future this will become a [SyntaxError](https://docs.python.org/3/library/exceptions.html#SyntaxError). This behaviour will happen even if it is a valid escape sequence for a regular expression.

> The solution is to use Python’s raw string notation for regular expression patterns; backslashes are not handled in any special way in a string literal prefixed with 'r'. So r"\n" is a two-character string containing '\' and 'n', while "\n" is a one-character string containing a newline. Usually patterns will be expressed in Python code using this raw string notation.

**Comment by newren** [comment]
Thanks for the heads up!  Fixed with cbc653569438 (filter-repo: pass raw bytestring to regex compilation, 2022-10-08)
