### ISSUE TITLE
Diverging history when rewriting cherry-picked commit

### ISSUE THREAD

**Issue by ackvf** [newren/git-filter-repo#386]
I spent several hours playing with this tool, learning how it works, experimenting with dozens of local repo copies, because I was receiving diverging histories when there was a cherry-picked commit referencing an old commit in its message.

All resulting from the updated commit message.

In the end, the solution was simple: use flag `--preserve-commit-hashes` to keep original unmodified messages (even though it means broken links).

What I can tell after all this struggle is that **I wish I was warned** by the tool, that commit messages were updated which might cause diverging histories when more repository instances are involved.

Normally, updating referenced hashes in commit messages is desired to maintain the link to their original commits, but it is critical that when such original commit is not reachable from main branch or pushed to origin, the message WILL NOT be updated. Perhaps, not updating commit messages might be even better turned off by default. Or new option that performs some assertions should be introduced.

Follows my original report, before I learned about the flag.

# Situation:

https://stackoverflow.com/q/73252581/985454

There is a **cherry-picked** commit merged in the `main` branch that references the original commit in the message:

>     FEAT-123: Add new feature
>
>     (cherry picked from commit abcdef1234567890)

Alice keeps in her local repo a backup of her original branch that contained the commit `abcdef1234567890`, however, this branch is not pushed to `origin`.

Bob does not have `abcdef1234567890` present in his local repo.

---

Both of them run a replace command followed by `git filter-repo --force` to make the changes permanent.

Alice observes that her original commit's hash (in the backup branch) is changed `abcdef1234567890` -> `11111111111112346`.
Alice then observes that the **cherry-picked** commit that is merged in the `main` now contains adjusted message.

>     FEAT-123: Add new feature
>
>     (cherry picked from commit 11111111111112346)

Bob does not observe these changes and for him, the merged **cherry-picked** commit keeps the original message.

>     FEAT-123: Add new feature
>
>     (cherry picked from commit abcdef1234567890)

**Alice and Bob then sync their repositories and discover that everything following (including) this cherry-picked commit is calculated with a different hash resulting in two parallel histories.**

---

Solution 1)

Alice pushes her local branch "backup" to `origin` so that everyone can fetch it and obtain the original commit `abcdef1234567890`.

Solution 2)

Alice deletes her local branch backup.

**Comment by newren** [comment]
Sorry for taking so long to respond.  This isn't the answer you want to hear, but having two people filter their respective clones and get the same new commit IDs is something that will never be reliable and supported.  A couple others have asked about it too, so I've added a FAQ and included this as one of the items in it: https://github.com/newren/git-filter-repo/blob/main/Documentation/FAQ.md#Filtering-two-different-clones-of-the-same-repository-and-getting-the-same-new-commit-IDs

**Comment by ackvf** [comment]
I see, I was under the impression that the hash was deterministic and indeed same when Alice and Bob run the filter, but I may have had wrong understanding of it back then or did simple enough tests that confirmed it by luck. Thank you for the response and adding it in FAQ.
