### ISSUE TITLE
@newren do you know about https://github.com/marketplace/actions/debugging-with-tmate? It makes debugging substantially easier, I find.

### ISSUE THREAD

**Issue by venum6** [newren/git-filter-repo#402]
@newren do you know about https://github.com/marketplace/actions/debugging-with-tmate? It makes debugging substantially easier, I find.

_Originally posted by @dscho in https://github.com/newren/git-filter-repo/issues/222#issuecomment-810571943_

**Comment by newren** [comment]
Stupid bots posting spam.  Account blocked.
