### ISSUE TITLE
Please support specifying filenames for callbacks

### ISSUE THREAD

**Issue by bdrung** [newren/git-filter-repo#403]
I have a long Python code for `--commit-callback` which is too long for passing as argument to `git-filter-repo`:
```
bash: /usr/bin/git-filter-repo: Argument list too long
```

Please support specifying filenames for the callbacks.

**Comment by newren** [comment]
It already does.  See #246 and 5256c99e496b (Allow callback body to be loaded from a file, 2021-04-27)

**Comment by bdrung** [comment]
Great. I looked at the man page and did not find anything about the file support. Only the `--help` output has one sentence "Note that if BODY resolves to a filename, then the contents of that file will be used as the BODY in the callback function.".

Can you extent the man page with this information? Especially in the "Generic callback code snippets" section, it could say "Python code body or filename for" instead of "Python code body for".
