### ISSUE TITLE
GIt filter repo remote: Internal Server Error 

### ISSUE THREAD

**Issue by lirantev** [newren/git-filter-repo#408]
Hi all,
I know this question was answered before regarding the Internal Server Error after using git filter repo to clean big repositories. I'm here for a better understanding of the git filter-repo command.
Background: we have a 12 GB repository on TFS which contains lots of big files (one of the files is 1.6GB alone) and we now in the process of moving this repo to GitHub. To decrease the size of the repo so we can push it to GitHub, we're using both git filter-repo and git lfs.
Since our repo also contains ~ 1400 branches and 2000 tags, the first stage is to delete most of the branches, so we're left with ~350 branches.
Then we're using `git filter-repo` to delete unnecessary files, so we're  only using `git filter-repo --invert-paths` command.
After running this command, I've executed `git-sizer --verbose` and found out we now have ~35.3k Other references, which I think most, if not all of them, are refs/replace. 
Those Other references are, for my understanding, is the root cause of getting the "remote: Internal Server Error" when trying to push this repository to GitHub (after using `git lfs` to move files to git lfs over JFrog articatory).
My question is, do I need to keep those refs/replace references or can I remove them using one of the `--replace-refs` options?
I'm not expert in Git and not sure what those refs/replace are, or if I need them if my goal is only to remove unwanted files so the repo size will be less than 2GB before pushing it to GitHub.
Thanks :)

**Comment by newren** [comment]
You don't need the replace refs; they are written for folks who started with Git and who want to do a rewrite, but who still want to be able to access commits using their old names (i.e. old hashes).  That's not relevant to you.  So, you can either delete the replace refs after the fact, or pass either `update-no-add` or `delete-no-add` option to `--replace-refs` when doing the rewriting.

**Comment by lirantev** [comment]
Hi @newren,
thank you for the replay 👍 
Liran.
