### ISSUE TITLE
Install to Debian 9 Stretch fails with dependency problems

### ISSUE THREAD

**Issue by webmaster33** [newren/git-filter-repo#409]
On Linux Debian 9 Stretch I execute
`sudo apt install git-filter-repo`

I get dependency problems:
```
Reading packing lists... Done
Building a dependency tree
Reading status information... Done
Some packages could not be installed. This could mean that
requested an impossible state, or if the unstable distribution
use it, some requested packages have not yet been completed or are out
has been moved from Incoming.
The following information may help you resolve the issue:

The following packages have unfulfilled dependencies:
  git-filter-repo : Depends on: git (>= 1:2.22) but only 1:2.11.0-3+deb9u7 can be installed
                    Recommend: git (>= 1:2.28) but only 1:2.11.0-3+deb9u7 can be installed
E: The problems cannot be fixed, damaged packages were returned.
```

I removed installed git v2.1.1 and built from source git v2.28.0.

```
git --version
git version 2.28.0
```

But still I get the same dependency problem, when I execute
`sudo apt install git-filter-repo`

I tried other suggested install solutions (except manual download), but still no success.

How to make Linux install work?
Any solution to install automatically (except manual way)?

**Comment by newren** [comment]
> On Linux Debian 9 Stretch I execute `sudo apt install git-filter-repo`
> 
> I get dependency problems:

apt issues need to be reported to Debian; I have no control over such issues.


> I removed installed git v2.1.1 and built from source git v2.28.0.
> 
> ```
> git --version
> git version 2.28.0
> ```
> 
> But still I get the same dependency problem, when I execute `sudo apt install git-filter-repo`

Right, you manually built git and apt has no idea you have a newer version of git installed.

> I tried other suggested install solutions (except manual download), but still no success.
> 
> How to make Linux install work? Any solution to install automatically (except manual way)?

You're quite curious.  You're willing to build a manual version of git, but not git-filter-repo?  A manual install of git filter-repo consists of [downloading a single file](../blob/main/INSTALL.md#simple-installation); you can't get much easier than that.

However, if you want apt to work on your particular Debian flavor, you'll need to talk to Debian.
