### ISSUE TITLE
Documentation mentions .sub() function on bytes which doesn't exist.

### ISSUE THREAD

**Issue by otac0n** [newren/git-filter-repo#41]
From what I've gathered, `.sub()` appears to be a regex specific function.  I believe the correct function for the 'bytes' type is `.replace()`.

e.g.

```
  blob.data = blob.data.sub(b"Hello", b"Goodbye")
```

should instead be

```
  blob.data = blob.data.replace(b"Hello", b"Goodbye")
```

**Comment by newren** [comment]
Indeed, you can call bytes.replace(old, new) or re.sub(regex, replacement, old), but you can't mix-and-match and call bytes.sub().  Whoops.  Fixed now; thanks for the report.
