### ISSUE TITLE
Commits turned empty or merges turned degenerate by blob-callback are not automatically removed.

### ISSUE THREAD

**Issue by otac0n** [newren/git-filter-repo#42]
With `git filter-repo --blob-callback '...'` I noticed that empty commits and merges were left after updating the file to match the previous commit.

*Workaround*
You can execute `git filter-repo --prune-empty always --prune-degenerate always` afterwards, providing you do not intend to keep any of the existing empty/degenerate commits.

**Comment by newren** [comment]
Could you provide an example?

When I create a simple repo with two commits:
```
git init foobar
cd foobar
touch a b c
git add .
git commit -m init
echo tiger >d
git add d
git commit -m 'Second commit'
```
then `git rev-list --count HEAD` reports two, noting that I have two commits.  If I then run filter branch to nuke any file whose contents is exactly b"tiger\n":
```
git filter-repo --force --blob-callback 'if blob.data == b"tiger\n": blob.skip()'
```
then after running the second commit (which just added a file named 'd' whose contents were 'tiger\n') is pruned and I have a repo with just one commit.

**Comment by otac0n** [comment]
git init foobar
cd foobar
echo a >a
echo b >>a
git add a
git commit -m init
echo a >a
echo remove >>a
echo b >>a
git add a
git commit -m 'Second commit'
git filter-repo --force --blob-callback '
  blob.data = blob.data.replace(b"\nremove", b"")
'

**Comment by newren** [comment]
Ah, I see.  Thanks for the steps to reproduce.  I'm guessing there's something wrong with the changed_files and self._files_tweaked logic.  I don't have time to investigate further right now, but I'll try to address it when I get some free time.

**Comment by newren** [comment]
I just pushed a fix for this; thanks for the report!
