### ISSUE TITLE
commit-callback not called

### ISSUE THREAD

**Issue by f-zl** [newren/git-filter-repo#428]
I clone a mini repo to test my commit-callback script and nothing happens. So I execute the following command to test commit-callback.

`git filter-repo --commit-callback 's=f"{commit.file_changes}";print(s);f=open("filter.log","w");f.write(s);f.close()'`

I expect something is printed in stdout, and a file `filter.log` is created. But neither happens. What is going wrong?

stdout shows
> Parsed 1 commits
> New history written in 0.22 seconds; now repacking/cleaning...
> Repacking your repo and cleaning out old unneeded objects
> HEAD is now at e788d8f Add a.txt
> Enumerating objects: 3, done.
> Counting objects: 100% (3/3), done.
> Writing objects: 100% (3/3), done.
> Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
> Completely finished after 0.48 seconds.

git version 2.33.1.windows.1
`git-filter-repo --version` shows ae71fad1d03f
Python 3.10.0

**Comment by newren** [comment]
I don't know.  Over here with a simple repo and that exact same command line, I see:
```
$ git filter-repo --commit-callback 's=f"{commit.file_changes}";print(s);f=open("filter.log","w");f.write(s);f.close()' --force
[<__main__.FileChange object at 0x7f9e74c8c310>]
[<__main__.FileChange object at 0x7f9e74c8c4d0>]
[<__main__.FileChange object at 0x7f9e74c8c4d0>]
[<__main__.FileChange object at 0x7f9e74c8c4d0>]
[<__main__.FileChange object at 0x7f9e74c8c590>]
[<__main__.FileChange object at 0x7f9e74c8c590>]
Parsed 6 commits
New history written in 0.02 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at 5fa4e05 greet everybody
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (14/14), done.
Total 14 (delta 3), reused 0 (delta 0), pack-reused 0
Completely finished after 0.10 seconds.
$ cat filter.log 
[<__main__.FileChange object at 0x7f9e74c8c590>][newren@iron-rod stupid (C)]$ 
$
```

So stdout is written and `filter.log` is clearly created.  Does windows mess up your command line somehow or something?  What does
```
echo git filter-repo --commit-callback 's=f"{commit.file_changes}";print(s);f=open("filter.log","w");f.write(s);f.close()'
```
report for you?

Can you duplicate this problem on a Mac or Linux system?

**Comment by f-zl** [comment]
Thanks for the reply. `echo git filter-repo --commit-callback 's=f"{commit.file_changes}";print(s);f=open("filter.log","w");f.write(s);f.close()'` gives `git filter-repo --commit-callback 's=f"{commit.file_changes}";print(s);f=open("filter.log","w");f.write(s);f.close()'`.

I find the command works in git-bash, but fails in git-cmd or cmd.exe. Maybe it's a problem in git-cmd.

**Comment by me-and** [comment]
That will be due to cmd having very different handling of quotes. The command you're trying to use is using a quote style that will only work in Bash (or other similar shells); cmd has significantly different behaviour.

**Comment by f-zl** [comment]
Thanks. In cmd or Powershell, one may escape a doThanks. In cmd or Powershell, one may escape a double quote `\"` to pass it to the program.uble quote `\"` to pass it to the program.

**Comment by Wilke-Oncken** [comment]
I also have the problem, that the script doesn't seem to be called at all. 

`λ git filter-repo --commit-callback 's=f\"{commit.file_changes}\";print(s);f=open(\"filter.log\",\"w\");f.write(s);f.close()' --force
Parsed 22951 commits
New history written in 13.00 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at dfa65b4c9 added custom rules
Enumerating objects: 196343, done.
Counting objects: 100% (196343/196343), done.
Delta compression using up to 32 threads
Compressing objects: 100% (35985/35985), done.
Writing objects: 100% (196343/196343), done.
Total 196343 (delta 156688), reused 196343 (delta 156688), pack-reused 0
Completely finished after 17.13 seconds.
`

I also run this on windows in a cmd console.  (cmder)
