### ISSUE TITLE
--email-callback doesn't work (CMD on Windows doesn't treat single quote, ['], as a quote mark)

### ISSUE THREAD

**Issue by user4302** [newren/git-filter-repo#435]
using the following syntax
`git-filter-repo --email-callback 'return email.replace(b".cm", b".com")'`

i try out `git-filter-repo --email-callback 'return email.replace(b"user@email.com", b"user.name@email.com")'`
but i get the following error
`git-filter-repo: error: unrecognized arguments: email.replace(buser@email.com, buser.name@email.com)'`

so i try this
`git-filter-repo --email-callback 'return email.replace(b"""user@email.com""", b"""user.name@email.com""")'`

but i get this 
`git-filter-repo: error: unrecognized arguments: email.replace(b"user@email.com", b"user.name@email.com")'`

what am i doing wrong?

**Comment by me-and** [comment]
This looks like a quoting problem. Can you confirm what shell you're using (Bash, PowerShell, cmd, …) and provide a complete copy-paste of the command and output as you see it?

**Comment by user4302** [comment]
> This looks like a quoting problem. Can you confirm what shell you're using (Bash, PowerShell, cmd, …) and provide a complete copy-paste of the command and output as you see it?

i am using CMD.

i tried this just now and it did not work
![image](https://user-images.githubusercontent.com/32593782/222623369-ea520135-b389-42ce-a6ff-c7f7f89af333.png)

i also forgot to add the who0le code for the issue,
i am using `python` (v3.10.2) in front of the `git-filter-repo` part
(i set it up to use "python" instead of "python3")

**Comment by user4302** [comment]
i am using CMD.

i tried this just now and it did not work
![image](https://user-images.githubusercontent.com/32593782/222623721-b1e15761-63c3-4339-b5d6-acf4f5a8637d.png)

i also forgot to add the who0le code for the issue,
i am using python (v3.10.2) in front of the git-filter-repo part
(i set it up to use "python" instead of "python3")

**Comment by andry81** [comment]
In CMD `'` character is not quote character. You must use `"` instead:

```cmd
python.exe git-filter-repo ... "return ..."
```

In Windows the nested quote character as the entire command line depends on the application contained in the command line being executed (child process), when in Linux - on the application has executed the command line (parent process).

Try something like:

* `\"`
* `"""`

```cmd
python.exe git-filter-repo ... "return ... \" ... \""
```

Basically in Windows all `\"` in `"` skips by `CreateProcess` API and it's relatives.

**Comment by user4302** [comment]
> In CMD `'` character is not quote character. You must use `"` instead:
> 
> ```batchfile
> python.exe git-filter-repo ... "return ..."
> ```
> 
> In Windows the nested quote character as the entire command line depends on the application contained in the command line being executed (child process), when in Linux - on the application has executed the command line (parent process).
> 
> Try something like:
> 
> * `\"`
> * `"""`
> 
> ```batchfile
> python.exe git-filter-repo ... "return ... \" ... \""
> ```
> 
> Basically in Windows all `\"` in `"` skips by `CreateProcess` API and it's relatives.

i already tried the triple quotes and got this
`git-filter-repo --email-callback 'return email.replace(b"""user@email.com""", b"""user.name@email.com""")'`

for the backslash method i get the error still
`git-filter-repo: error: unrecognized arguments: email.replace(b"user@email.com", b"user.name@email.com")'`

**Comment by andry81** [comment]
Can you introduce the full command line you typed in console?

**Comment by user4302** [comment]
> git-filter-repo --email-callback 'return email.replace(b"user@email.com", b"user.name@email.com")'

yeah, here it is

`python git-filter-repo --email-callback 'return email.replace(b\"user@email.com\", b\"user.name@email.com\")'`

(previously i had `user@email.com` and made many commits and pushed to the repo
now i changed to `user.name@email.com` and have a few with this email address for the author.)

**Comment by andry81** [comment]
> python git-filter-repo --email-callback 'return email.replace(b\"user@email.com\", b\"user.name@email.com\")'

You didn't fix the command line, you still trying to use `'` as quote character.

**Comment by user4302** [comment]
> > python git-filter-repo --email-callback 'return email.replace(b"[user@email.com](mailto:user@email.com)", b"[user.name@email.com](mailto:user.name@email.com)")'
> 
> You didn't fix the command line, you still trying to use `'` as quote character.

ohhhh. around the whole command, i just noticed.
my bad.
its working now.
thanks loads.

also i tested this on a small dummy local repo and forced it and it works.

if i try this on a repo that is on gitlab.
when i run this command, will it ask me to make a new commit which will push all the files with updated authors?

**Comment by andry81** [comment]
> when i run this command, will it ask me to make a new commit which will push all the files with updated authors?
> i just dont want anything to break on the repo.

I don't know how would git-filter-repo act, but the old filter-branch just creates `refs/originals/refs/*` to be able to restore original branches and copy the rest references and tags.

**Comment by newren** [comment]
> if i try this on a repo that is on gitlab. when i run this command, will it ask me to make a new commit which will push all the files with updated authors? i just dont want anything to break on the repo.
> 
> i noticed an incorrect email address on sonarQube, which is why im trying to change my email now

When you run filter-repo, it modifies any commits matching the rules you specify, AND all commits which come after those in any branch.  If you were just fixing up the latest commit on some branch, force-pushing back to the resource might be okay.  But pushing a rewritten version of public history should not be something you undertake lightly; please read https://www.mankier.com/1/git-filter-repo#Discussion to get some background on the ramifications.  You may also want to see https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html#repository-cleanup for the steps to take if you need to purge the old commits.

> ohhhh. around the whole command, i just noticed.
> my bad.
> its working now.

Glad it's working for you now.  Thanks, both @me-and and @andry81.
