### ISSUE TITLE
Add basic installation instructions. 

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [newren/git-filter-repo#450]
Fulfilled by PR #449

I originally wrote the instructions here: https://github.com/rtyley/bfg-repo-cleaner/issues/255#issuecomment-1500711841

**Comment by newren** [comment]
I have never understood why people feel the need to open an issue when they've already opened a PR.  The PR is sufficient.

**Comment by ElectricRCAircraftGuy** [comment]
@newren , I've been told in the past by some repo owners that every PR should solve a problem described by some issue. So, if no issue exists for your PR, your PR is useless and will be rejected because it solves no documented task nor issue. If your PR isn't useless, then you should create an issue or task to describe the problem it is solving, then link to it from the PR. In this way, every PR has an issue attached to it. Some companies, corporations, project managers, or professional teams work this way too. 

That's why I did it. I imagine that's why others do it too.

Also, it has the added benefit of doubling the chance of it being seen.

**Comment by ElectricRCAircraftGuy** [comment]
One more really important reason: when people are searching for clearer, beginner-friendly instructions for "how to install `git filter-repo`, they are likely to search the issues, _not_ the pull requests for this information. So, I wanted to be sure to put it here to help them find it in case you reject the pull request, which you did.

**Comment by newren** [comment]
> @newren , I've been told in the past by some repo owners that every PR should solve a problem described by some issue. So, if no issue exists for your PR, your PR is useless and will be rejected because it solves no documented task nor issue. If your PR isn't useless, then you should create an issue or task to describe the problem it is solving, then link to it from the PR. In this way, every PR has an issue attached to it. Some companies, corporations, project managers, or professional teams work this way too and require this pattern.
> 
> That's why I did it--not because I naturally like this pattern, but because I've been trained to follow it. I imagine that's why others do it too. I don't necessarily subscribe to this pattern otherwise.

Ah, that's good info.  Thanks for letting me know.  Disappointing that other repo owners are encouraging suboptimal behavior (the commit messages should describe the problem being solved, not some external URL), but understandable that people respond by trying to be good citizens and make mistakes.

> Also, it has the added benefit of doubling the chance of it being seen.

Yeah, that'd be the kind of bad behavior I'd definitely want to curb.  Spamming to get attention, if it works, would lead to others doing the same and even upping the game.  It's a big waste of everyone's time.

> One more really important reason: when people are searching...

Hmm, this one I actually find reasonable, though I think it'd be better to create only if and after the corresponding PR is closed without merging.  If the PR is accepted, you've merely succeeded in generating spam and busywork by listing it in multiple places.

Anyway, thanks for taking the time to explain why.  Let's move the rest of the discussion to the PR, though.
