### ISSUE TITLE
Removed file still exist in analyze report

### ISSUE THREAD

**Issue by YuenSengTang** [newren/git-filter-repo#451]
Encounter a issues that the removed file still exist in the analyze report.
The step was:
1. git filter-repo --invert-paths --path  /path/to/MyFile.zip
2. git filter-repo --analyze --force 
3. open blob-shas-and-paths.txt and search the file name it still there. 

I had tried to check on the git log but it seems like all the history was deleted.

**Comment by andry81** [comment]
May be you should purge the history? Check the reflog.

**Comment by newren** [comment]
> 1. git filter-repo --invert-paths --path  /path/to/MyFile.zip

It is not possible for a repository to contain a path named `/path/to/MyFile.zip`, so if this is indeed what you used, it would remove nothing.  Did you perhaps intend to specify `path/to/MyFile.zip`?

> 2. git filter-repo --analyze --force
> 3. open blob-shas-and-paths.txt and search the file name it still there.

Which name is still there?  Was it actually the same one you specified to filter-repo, or was it different?  Hard to debug when you haven't specified actual filenames or commands, but I'm wondering if you munged the filename somewhere by adding a leading `/`.

> I had tried to check on the git log but it seems like all the history was deleted.

git log with which arguments?  By default, `git log` only shows the history of HEAD, not of other branches or tags.

**Comment by newren** [comment]
> May be you should purge the history? Check the reflog.

git-filter-repo purges reflog by default, so unless we know they were using arguments associated with a partial history rewrite (suggesting they used flags other than what they said they did in the original report), this is an unlikely to be useful guess at what's wrong.
