### ISSUE TITLE
Iterate through commits running conversion on file

### ISSUE THREAD

**Issue by mpias670** [newren/git-filter-repo#478]
### Discussed in https://github.com/newren/git-filter-repo/discussions/475

<div type='discussions-op-text'>

<sup>Originally posted by **mpias670** June  1, 2023</sup>
``Long story short, I have a repository with a bunch of commits containing a single .eapx file that I need to convert to .qeax. 

Using an .exe called Lemontree Automation, my goal is to go commit by commit converting this .eapx to .qeax. I know how to do the conversion part, what I don't know how to do is iterate through each commit on each branch, dump the old .eapx file, and add the .qeax file. Anyone have insight on the iteration, removing, and adding pieces below?

**The goal is this:**

```
for each branch:  
     for each commit:  
          convert eapx -> qeax  
          remove .eapx  
          add .qeax  
```
</div>

**Comment by newren** [comment]
No reason to have both an issue and a discussion open for the same topic.  Closing this since the discussion was opened first.
