### ISSUE TITLE
Question: Make history linear ?

### ISSUE THREAD

**Issue by idanmiara** [newren/git-filter-repo#493]
Hi,
My filtered repo has merge commits, thus I cannot squash some old successive `wip` commits in order to cleanup history.
Is there an option to linearize the history so I can squash them?
I know that in some cases it might not be trivial, but in some other cases if the merge commit could have been just fast-forward, maybe it's possible to linearize naively ?
Thanks!

**Comment by newren** [comment]
This seems more like a job for `git rebase`, honestly.  You could try to write specialized filters to handle removing the special degenerate merge cases, but nothing exists natively in filter-repo for this, and that wouldn't clean up the old `wip` commits you had even if you did write such a thing.  `git rebase` (possibly with the `--rebase-merges` flag if there are some merges you want to preserve just not all of them) seems like a better tool here.
