### ISSUE TITLE
[Thanks] How to revert the command ?

### ISSUE THREAD

**Issue by ThePredators** [newren/git-filter-repo#505]
Hello,

I accidently run the `git filter-repo` on my repo and it deleted everything !!!! 

Please how can i revert this ????

**Comment by ThePredators** [comment]
You can be proud of yourself guys u made a tool that delete everything in a repo not only history but even files. And no software or anything can revert what you achieved !! 

Great job guys !!!

**Comment by bryceschober** [comment]
Please take your shaming somewhere else, preferably the waste bin. The program clearly warns you of the consequences of your choices, which required you to `--force` the operation.

**Comment by newren** [comment]
The first two sentences of the manual are:
```
Rapidly rewrite entire repository history using user-specified filters.
This is a destructive operation which should not be used lightly...
```

Also, the first two sentences of the built-in simplified help printed by `git filter-repo -h` says
```
git-filter-repo destructively rewrites history (unless --analyze or
--dry-run are given) according to specified rules. It refuses to do any
rewriting unless either run from a clean fresh clone, or --force was
given.
```

Also, even if you don't read the documentation, if git-filter-repo detects that you are not running within a fresh clone, the command aborts and prints the following message:
```
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
  <further detail about why it appears not to be a fresh clone>
Please operate on a fresh clone instead.  If you want to proceed
anyway, use --force.
```

Finally, the --force flag is documented as

```
Rewrite repository history even if the current repo
does not look like a fresh clone.  History rewriting is
irreversible...
```

It sounds like what happened here are that you ignored the manual, you ignored the built-in help, you were not in a fresh clone, but you copy & pasted a command online using the `--force` flag, but you didn't bother to check what the `--force` flag was documented as, and didn't check that the command given online only made the types of changes that you wanted, but ran it anyway.  That stinks.  Much like folks who run `rm -rf ${DIRECTORY}` it leaves you with a big sinking feeling.  It is not fun to be in that situation.  But there are absolutely cases where `rm -rf ${DIRECTORY}` is needed, and cases where the git filter-repo command with various flags are needed.  I am sorry you decided to use a destructive tool without understanding what it does or paying any attention to the multiple levels of warnings it attempted to provide.  That's no fun.
