### ISSUE TITLE
Question: How to filter content of a specific file

### ISSUE THREAD

**Issue by amitdo** [newren/git-filter-repo#509]
Hi,

Is there a way to use `--replace-text` or `--blob-callback` and restrict it to filter a specific filename (e.g.` path/to/Makefile.am`) ?

**Comment by newren** [comment]
The new --file-info-callback added in commit 615720731589 (filter-repo: add a --file-info-callback, 2024-10-23) permits doing this.  That commit adds a callback which allows you to work with both the filename and file contents (and file mode), and includes the ability to apply the replacement text only to files of your choosing from within the callback.

**Comment by amitdo** [comment]
Thanks!
