### ISSUE TITLE
the `--version` test is broken

### ISSUE THREAD

**Issue by Humm42** [newren/git-filter-repo#513]
`git-filter-repo --version` restores the original shebang and `@@LOCALEDIR@@` before giving itself to `git hash-object`, ensuring such changes don’t affect the version. The test t/t9390-filter-repo.sh:1803 “--version” compares the output given by `git-filter-repo --version` with that of `git hash-object git-filter-repo`.

If no shebang or `@@LOCALEDIR@@` replacement is made or it’s made after running the test, the undoing that replacement is not tested.

If the shebang or `@@LOCALEDIR@@` is replaced before running the test, it fails.

**Comment by newren** [comment]
Should be fixed by ac5040504407 (t9390: skip the version test if we are in some kind of installation, 2024-08-02); thanks for the report.
