### ISSUE TITLE
FileExistsError: File already exists: /bin/git-filter-repo

### ISSUE THREAD

**Issue by milahu** [newren/git-filter-repo#515]
setup.cfg conflicts with setup.py

https://github.com/newren/git-filter-repo/blob/4bc9022afce5e2e138596bbecf4df310212ae164/release/setup.cfg#L26

https://github.com/newren/git-filter-repo/blob/4bc9022afce5e2e138596bbecf4df310212ae164/release/setup.py#L21

error:

```
$ python3 -m installer --prefix prefix-git-filter-repo-2.38.0 git_filter_repo-2.38.0-py2.py3-none-any.whl
FileExistsError: File already exists: /nix/store/4zvcw3cg9mhgbak9ylpb890gs2pp2kwz-python3.10-git-filter-repo-2.38.0/bin/git-filter-repo
```

fix: [remove](https://github.com/milahu/nur-packages/commit/7d7366d068f2c9a27b5978398c2eb3c74abe76fb) the `scripts = git-filter-repo` line from setup.cfg

the build of the same version of git-filter-repo has worked before
so i blame the new python installer (python3.10-installer-0.7.0)

my build script is [git-filter-repo.nix](https://github.com/milahu/nur-packages/blob/master/pkgs/development/python-modules/git-filter-repo/git-filter-repo.nix)

**Comment by newren** [comment]
setup.cfg and setup.py were nuked in 2c9cc90609a7 (Modernize and simplify Python packaging, 2023-09-24); did that commit resolve things for you, or is there still a problem?

**Comment by milahu** [comment]
yes, fixed by [updating](https://github.com/milahu/nur-packages/commit/c74b8f143d2544703adce2af8bafae268f1c1d7a)
