### ISSUE TITLE
Commit messages that don't have terminal newline always get a newline appended regardless of options

### ISSUE THREAD

**Issue by KevOrr** [newren/git-filter-repo#516]
Running `git-filter-repo --dry-run` (as well as other no-op invocations such as `git-filter-repo --dry-run --blob-callback 'pass'` and `git-filter-repo --dry-run --commit-callback 'pass'`, and other invocations that perform more useful changes) on https://github.com/KevOrr/dotfiles causes some erroneous changes to commits, such as:

```
commit refs/heads/master
mark :96
original-oid 3b9cbd0098b44ab095e0b23f22a60c9d52606bb8
author Kevin Orr <KevOrr@users.noreply.github.com> 1520647667 -0500
committer GitHub <noreply@github.com> 1520647667 -0500
data 40
[setup] Fixed some system package errorsfrom :95
M 100644 a367bfb137579cef305cc881720d98c27f0685ff dotfiles/setup
```
```
commit refs/heads/master
mark :96
author Kevin Orr <KevOrr@users.noreply.github.com> 1520647667 -0500
committer GitHub <noreply@github.com> 1520647667 -0500
data 40
[setup] Fixed some system package errors
from :95
M 100644 a367bfb137579cef305cc881720d98c27f0685ff dotfiles/setup
```

Calling `git-filter-repo --dry-run --commit-callback 'print(commit.message)'` confirms that the problematic commits have commit messages without terminal newlines:

```sh
$ git-filter-repo --dry-run --commit-callback 'print(commit.message)'
...
b"[setup] Don't create ssh key if it exists\n"
b'[setup] Fixed some system package errors'
b'[setup] Changed python build requirements to use builddep'
```

Running git-filter-repo on this project causes these commits' messages to change, which changes more hashes than necessary.

Based on the author and committer emails, I think I must have used the GitHub web editor to make these commits. I'm not sure if other porcelains might also produce messages that don't have a terminal newline.

**Comment by newren** [comment]
> Running `git-filter-repo --dry-run` (as well as other no-op invocations such as `git-filter-repo --dry-run --blob-callback 'pass'` and `git-filter-repo --dry-run --commit-callback 'pass'`, and other invocations that perform more useful changes) on https://github.com/KevOrr/dotfiles causes some erroneous changes to commits, such as:
> 
> ```
> commit refs/heads/master
> mark :96
> original-oid 3b9cbd0098b44ab095e0b23f22a60c9d52606bb8
> author Kevin Orr <KevOrr@users.noreply.github.com> 1520647667 -0500
> committer GitHub <noreply@github.com> 1520647667 -0500
> data 40
> [setup] Fixed some system package errorsfrom :95
> M 100644 a367bfb137579cef305cc881720d98c27f0685ff dotfiles/setup
> ```
> 
> ```
> commit refs/heads/master
> mark :96
> author Kevin Orr <KevOrr@users.noreply.github.com> 1520647667 -0500
> committer GitHub <noreply@github.com> 1520647667 -0500
> data 40
> [setup] Fixed some system package errors
> from :95
> M 100644 a367bfb137579cef305cc881720d98c27f0685ff dotfiles/setup
> ```

Sorry, there's no change here as far as what is imported.  git-fast-import allows a trailing newline that it'll ignore, so the important bit is how much of the commit message string is meant to be included.  If you'll notice, there's a `data 40` directive found in both cases, which means that the commit message is the exact same length.  The trailing newline was added solely for legibility of the `--dry-run` output (see https://github.com/newren/git-filter-repo/blob/4bc9022afce5e2e138596bbecf4df310212ae164/git-filter-repo#L693-L713).

> Calling `git-filter-repo --dry-run --commit-callback 'print(commit.message)'` confirms that the problematic commits have commit messages without terminal newlines:
> 
> ```shell
> $ git-filter-repo --dry-run --commit-callback 'print(commit.message)'
> ...
> b"[setup] Don't create ssh key if it exists\n"
> b'[setup] Fixed some system package errors'
> b'[setup] Changed python build requirements to use builddep'
> ```
> 
> Running git-filter-repo on this project causes these commits' messages to change, which changes more hashes than necessary.

As noted above, the newline in the `--dry-run` output is not the cause of you getting a different hash.  The following is what is causing you to get different commit hashes:

```
 git cat-file -p 3b9cbd0098b44ab095e0b23f22a60c9d52606bb8
tree 45de8c379bbf2a2d1c65c81ada886f54b6b97550
parent e4ae97f200f54c14f3f15fd3d73ba2d4186dba91
author Kevin Orr <KevOrr@users.noreply.github.com> 1520647667 -0500
committer GitHub <noreply@github.com> 1520647667 -0500
gpgsig -----BEGIN PGP SIGNATURE-----
 
 wsBcBAABCAAQBQJaoz3zCRBK7hj4Ov3rIwAAdHIIAD0Y8oRB0T2T5ZRPv/edgtbW
 fHdS2kqKffJA6ZPzK+0HXEsiJC57CGYYASEOmpm5L0R7LGUU//WHH3rqiKp3EQfs
 XsJ61Rb+87XMwmiwBgDhG5tMssTjqsFk1nfj8/DnsBRyFRZ3tAtUjuhq/ihkoPNg
 4jgEHlErt3xc7PlP9AJzObFjvyF21R4KbyciKFXAfTU2WfgQyIPIMVe1GXs/8LJW
 SLGX1/zBlfoiE1/nlsjD5OU0vVsbMv5DMsrbsbJROWD7FEFXJGZuDGzid1ixvS1G
 lQgGkhA7LSQa4eLxQIcY5hX1yixOSdf+x83OOEm5W9oCPXsMKAUCBzp7twT7NoY=
 =m0RG
 -----END PGP SIGNATURE-----
```

See the gpg signature?  fast-export and fast-import strip those, and since filter-repo works by calling fast-export & fast-import, it inherits that limitation.  Perhaps I could make the following part of the manual clearer:
```
Inherited limitations

Since git filter-repo calls fast-export and fast-import to do a lot of the heavy lifting, it inherits limitations from those systems:

* extended commit headers, if any, are stripped
```

In particular, gpg signatures are an extended commit header; maybe I should call it out as a special case.

As an alternative, you could specify a range of refs to operate with `--refs`, if you know you only want it to tweak newer commits.

**Comment by KevOrr** [comment]
> Sorry, there's no change here as far as what is imported

Oh man, what a red herring that was.

> The following is what is causing you to get different commit hashes

Ahhhhh okay, I never would have thought to look at the actual commit objects. I thought fast-export could serialize all that there is about an object. That's too bad. But the addition to the git-filter-repo docs looks nice. Though, I was so sure this had to be a bug that my first thought was to search open and closed issues for this. So in that case I'm not sure I would have thought to check the readme.

Hmm, maybe a printed warning if any extended headers were encountered? Or does fast-export just silently skip over those without telling the caller somehow?

> As an alternative, you could specify a range of refs to operate with `--refs`, if you know you only want it to tweak newer commits.

Wow, this worked! I didn't realize `--refs` could take a range, but now I see that line in the manpage.

Thanks for the support. I know partial history rewrites aren't meant to be supported as well as full history rewrites, so I appreciate the help with this lower priority feature.
