### ISSUE TITLE
How to keep the file in the file system with filter-repo?

### ISSUE THREAD

**Issue by ruslaniv** [newren/git-filter-repo#527]
I have successfully ran git-filter-repo as
```
git filter-repo --invert-paths --path server/apps/main/external_sources/file.py --force
```
It did exactly what I wanted it to do, it removed all references to that file from the commit history in my branch.

But it also seems to completely has removed any references to that file **AND** deleted that file from the hard drive. 

So when I tried to 
```
git checkout origin/master server/apps/main/external_sources/file.py
```
it errored out with unknown file, although I was working in my specific branch (where this specific file did not belong in the commit history)

So I tried deleting the local branch I was working in and checked out the branch from remote - it also did not have that file.
I even deleted local master and checked out master from remote - the file still was not there! 
I checked the actual file structure via explorer and the file was not there.

Why did it delete the file and somehow makes it impossible to bring that file back into the project structure? 

Here is how I saw the workflow:
1. I create a branch and do some work
2. I accidently add a file that does not belong in this branch
3. I do some more work
4. I run filter-repo and completely remove the file from the git commit history
5. Now the commit history looks like this file was never part of my work in this branch
6. I create a new branch, bring that file over and there I add that file into commit history

I guess my understanding of the tool is incorrect?

**Comment by AlexeyDmitriev** [comment]
From the docs

> Since filter-repo does irreversible rewriting of history, it is important to avoid making changes to a repo for which the user doesn’t have a good backup.

Also, you explicitely used `--force` to avoid fresh checks...

**Comment by newren** [comment]
> It did exactly what I wanted it to do, it removed all references to that file from the commit history in my branch.

No, the tool is called filter-repo, not filter-branch.  It removed all references to that file from the commit history in your local **_repo_**.

Now, it does have options to only work on certain branches (e.g. `--refs`), but those are not the default.

This command only updates your local clone, and leaves it up to you to (force) push the results to any other copies of the clone, including the location you cloned from.  So, if you really did want this file to still be present in your remote tracking branches, you could just refetch those remote tracking branches from your remote repository that you had cloned from (e.g. `git remote add origin ${ORIGINAL_CLONE_URL} && git fetch origin`).

I'll assume that answers your questions, but feel free to reopen if that still isn't clear (though let me know what's unclear about it).

**Comment by FDUguchunhui** [comment]
> > It did exactly what I wanted it to do, it removed all references to that file from the commit history in my branch.
> 
> No, the tool is called filter-repo, not filter-branch. It removed all references to that file from the commit history in your local **_repo_**.
> 
> Now, it does have options to only work on certain branches (e.g. `--refs`), but those are not the default.
> 
> This command only updates your local clone, and leaves it up to you to (force) push the results to any other copies of the clone, including the location you cloned from. So, if you really did want this file to still be present in your remote tracking branches, you could just refetch those remote tracking branches from your remote repository that you had cloned from (e.g. `git remote add origin ${ORIGINAL_CLONE_URL} && git fetch origin`).
> 
> I'll assume that answers your questions, but feel free to reopen if that still isn't clear (though let me know what's unclear about it).

I have the same question. What if you don't know it deletes files instead of just removing them from the commit history and then forcing the commit to the remote? Is there a way to recover those deleted files in this case?

**Comment by newren** [comment]
> What if you don't know it deletes files instead of just removing them from the commit history and then forcing the commit to the remote? Is there a way to recover those deleted files in this case?

You started by making a fresh clone of your repository, and only rewriting history on that fresh clone, as suggested in the instructions -- right?  If so, just throw the clone away and make a new one.  If you didn't do this and you used the `--force` flag to override the fresh clone check, see
https://github.com/newren/git-filter-repo/issues/606#issuecomment-2426798122
