### ISSUE TITLE
Callback that gives both filename and blob

### ISSUE THREAD

**Issue by AlexeyDmitriev** [newren/git-filter-repo#549]
So, I'd like to minimize blobs depending on their type, i.e if file has specific extension, then do something with it, otherwise leave it as is.

it seems I can't, filename-callback allow only removing/renaming file and --blob-callback already loses information on filename

Maybe I can with commit-callback but it seems rather convoluted (and also I didn't quite get how all the fields work)

I would suggest making a --file-callback that will give a blob along with path in the repo. Maybe there's a better solution

**Comment by newren** [comment]
The new --file-info-callback added in commit 615720731589 (filter-repo: add a --file-info-callback, 2024-10-23) does exactly this.  So I almost implemented your feature request, but I named the callback slightly differently.

**Comment by cirosantilli** [comment]
Related: https://github.com/newren/git-filter-repo/issues/158 Cool to see that his was done.
