### ISSUE TITLE
Test suite succedes with Python 3.11 but has multiple failures with Python 3.12

### ISSUE THREAD

**Issue by alerque** [newren/git-filter-repo#554]
I'm trying to rebuild Arch Linux packages with Python 3.12 and running into problems with the test suite. Everything was good with 3.11, but with 3.12 there are many failures. I don't even see how to get error messages out of the test suite, it just echos the code of the failing test. For example the first one is from `t9390-filter-repo.sh` "not ok 29", but there are more.

Does anybody know what's up or even how to figure out what's might be up?

**Comment by knuxify** [comment]
Hit the same issue on Alpine Linux. It seems that #526 fixes failures 29, 51, 63 and 64, but not 36.

**Comment by knuxify** [comment]
Test 36 is fixed by adding rsync to checkdepends.

**Comment by amitdo** [comment]
@knuxify,

Could you please add a PR?

@newren is not responding to issues & PRs in the last months. Maybe he is busy... But if a patch is available people can apply it to their fork.

**Comment by knuxify** [comment]
The test 36 failure (missing rsync) was the fault of my own setup (forgot to install it), "adding rsync to checkdepends" is to be done on the package's side (just make sure it's installed if you run the tests is what I meant). As for the other failures, #526 fixes those.

**Comment by newren** [comment]
#526 was fixed a couple weeks ago with 7c5be8e30355 (Support git 2.43, 2023-12-08).  The rsync issues are outside the scope of this project.  The tests all pass on Python 3.12 for me with the fix to #526.

Sorry for the delay here from my extended absence.

**Comment by alerque** [comment]
Great! Thanks for the work on that.

Now we just need a new release so we can package it properly without a bunch of backport shenanigans.

**Comment by newren** [comment]
> Now we just need a new release so we can package it properly without a bunch of backport shenanigans.

Yep, totally understood.  There are more issues in the backlog than this, though, and some PRs as well, and I'd like to at least catch up on the backlog a bit before cutting a release.  Thanks for your patience.
