### ISSUE TITLE
Turns out my assumption was wrong: `git lfs migrate export --everything --include="*"` does rewrite the whole history, across all branches, reinjecting all the large files' consecutive versions ([see here](https://github.com/git-lfs/git-lfs/issues/910#issuecomment-551566315)). Awesome!

### ISSUE THREAD

**Issue by cklim033** [newren/git-filter-repo#555]
Turns out my assumption was wrong: `git lfs migrate export --everything --include="*"` does rewrite the whole history, across all branches, reinjecting all the large files' consecutive versions ([see here](https://github.com/git-lfs/git-lfs/issues/910#issuecomment-551566315)). Awesome!
Thanks for the info anyway! So far I'm super impressed by filter-repo's speed, I'm pondering if it could be used to replace git-subtree (which for my use is really lacking).

_Originally posted by @benblo in https://github.com/newren/git-filter-repo/issues/7#issuecomment-551416632_

**Comment by newren** [comment]
Stupid spam bot
