### ISSUE TITLE
Trouble with Lock File

### ISSUE THREAD

**Issue by danielkwalsh** [newren/git-filter-repo#566]
I'm getting the following error:
`fatal: cannot lock ref <REF>: Unable to create <ROOT>/.git/refs/heads/<BRANCH>.lock: File exists.`
Researching the problem online, it seems this error can occur if there's another git process working on the files concurrently, which can create another lock file. However, after receiving the error, I checked <ROOT>/.git/refs/heads/<BRANCH>.lock, and there was no such file. Any thoughts?

**Comment by newren** [comment]
You're running on a case-insensitive filesystem, but have branches that differ only in case.  Do your filtering on a case-sensitive filesystem and it'll work just fine.  A search through the issues in this repository for the cannot lock message will find multiple duplicates.

**Comment by harshita-gupta** [comment]
I'm running into this error even on a case-sensitive filesystem: https://github.com/newren/git-filter-repo/issues/590

**Comment by newren** [comment]
> I'm running into this error even on a case-sensitive filesystem: [#590](https://github.com/newren/git-filter-repo/issues/590)

Nope, #590 is different.  That's locking packed-refs and additionally has the weird `./` in the path.  Let's keep these separate.
