### ISSUE TITLE
formatting repo with git-filter-repo

### ISSUE THREAD

**Issue by PavelPolyakov** [newren/git-filter-repo#57]
Good day,

First of all - thanks for the tool 🙇‍♂️. Recently `git` started to print a deprecation warning for `git filter-branch`, so I got here, while googling how to reformat my repo without a big format commit [🔗](https://medium.com/millennial-falcon-technology/reformatting-your-code-base-using-prettier-or-eslint-without-destroying-git-history-35052f3d853e). What I want to do is to rewrite history of the project applying formatting (new) to each commit.

After I read through the docs, I understand, that I can apply formatting by using `--blob-callback`. And that I can do some conditioning, based on the filenames, using `--filename-callback` or `--commit-callback`. But what I really want to do - apply formatting only for certain files, for example, if it has extension `.java`.

My question:
Given that in [`blob`](https://github.com/newren/git-filter-repo/blob/master/git-filter-repo#L495) the filename is not present and that in [`commit`](https://github.com/newren/git-filter-repo/blob/master/git-filter-repo#L623) - the blobs are not present, how can I change file content during the history rewrite based on the file name and other conditions?

Regards,

**Comment by newren** [comment]
This is basically the same question asked in #45, you may want to read through the comments in that issue.  The short version is that the script contrib/filter-repo-demos/lint-history in the git-filter-repo repository shows how to do this, though you may want to tweak it to add even more conditions.  (Alternatively, you could use lint-history as is to call some external script with the filename, then that external script decides to either run on the filename in question or simply return.)

Hope that helps,
Elijah
