### ISSUE TITLE
How to move every file in the root directory to a new subdirectory?

### ISSUE THREAD

**Issue by behrangsa** [newren/git-filter-repo#59]
This seems to delete everything:

```
git-filter-repo --path . --to-subdirectory-filter new-module --tag-rename '':'new-module-'
```

This doesn't seem to do anything:

```
git filter-repo --path-rename .:new-module
```

Any ideas how could this be done?

**Comment by newren** [comment]
What version of filter-repo are you using?  For the commands you gave, it should report an error of the form:
   Error: Invalid path component '.' found in '.:new-module'
Though that error wasn't added until git-filter-repo v2.25.0.

Anyway, just drop the `--path .` specification from the first command; you don't need to limit which paths you are working on if you are working with all of them.
