### ISSUE TITLE
file paths are not handled correctly when using under Cygwin with cygwin git but windows native python

### ISSUE THREAD

**Issue by rebroad** [newren/git-filter-repo#598]
This is perhaps more a feature request than a bug, but in a mixed environment where python (windows native) is being used from within Cygwin (which uses UNIX style paths) this fails.

**Comment by newren** [comment]
I don't understand what you're saying in the bug title.  Perhaps you could include an example command you are using, the results you are getting, and the results you expect?

**Comment by rebroad** [comment]
closing as perhaps this is a quirky edge-case (mixed environment between cygwin and windows native)
