### ISSUE TITLE
get_config_settings errors on blank lines returned by git config --list

### ISSUE THREAD

**Issue by GavinMasterson** [newren/git-filter-repo#603]
## Issue Description

When running `git filter-repo`, I get an error from the `get_config_settings` function.

## Cause

The output of line 1556's `subproc.check_output(git config --list.split(), cwd=repo_working_dir)` is equivalent to: 
```
output = b'''user.email=name@email.com
user.name=My Name

includeif.gitdir/i:~/work/.path=~/work/.gitconfig-work
user.email=name@workemail.com
user.name=My Name

credential.helper=cache
init.defaultbranch=main
includeif.hasconfig:remote.*.url:git@host.com:work/**.path=~/work/.gitconfig-work
credential.helper=cache
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true'''
```

The conversion of the `output` object to the returned `dict` fails with the message:
> Traceback (most recent call last):
  File "/usr/bin/git-filter-repo", line 4151, in <module>
    main()
  File "/usr/bin/git-filter-repo", line 4148, in main
    filter.run()
  File "/usr/bin/git-filter-repo", line 4068, in run
    self._run_sanity_checks()
  File "/usr/bin/git-filter-repo", line 2931, in _run_sanity_checks
    self._config_settings = GitUtils.get_config_settings(target_working_dir)
  File "/usr/bin/git-filter-repo", line 1563, in get_config_settings
    return dict(line.split(b'=', maxsplit=1)
ValueError: dictionary update sequence element #2 has length 1; 2 is required

## Potential Solution

I fixed the issue by modifying the function as follows: 
```
@staticmethod
  def get_config_settings(repo_working_dir):
    output = ''
    try:
      output = subproc.check_output('git config --list'.split(),
                                    cwd=repo_working_dir)
    except subprocess.CalledProcessError as e: # pragma: no cover
      raise SystemExit('fatal: {}'.format(e))
    
    # Changes start here -->
    decoded_output = output.decode('utf-8')
    lines = [line for line in decoded_output.split('\n') if line.strip()]
    # FIXME: Ignores multi-valued keys, just let them overwrite for now
    return dict(line.split('=', maxsplit=1) for line in lines if '=' in line)
``` 

There are probably better ways to solve the issue that do not involve an opinionated decoding step, as I cannot tell what side-effects the decoding step may have in repos that are not UTF-8 encoded.

## Summary

When running my desired `git filter-repo ...` command with this function, the command works as intended, and raises no error.

**Comment by GavinMasterson** [comment]
Thanks for your response. I investigated again, and it appears that in both cases of my `.gitconfig`, my editor added a string literal `\n` to may username somehow 🤦.  

I am so sorry to have wasted your time.

**Comment by xiaohk** [comment]
> > The output of line 1556's `subproc.check_output(git config --list.split(), cwd=repo_working_dir)` is equivalent to:
> > ```
> > output = b'''user.email=name@email.com
> > user.name=My Name
> > 
> > includeif.gitdir/i:~/work/.path=~/work/.gitconfig-work
> > user.email=name@workemail.com
> > user.name=My Name
> > 
> > credential.helper=cache
> > init.defaultbranch=main
> > includeif.hasconfig:remote.*.url:git@host.com:work/**.path=~/work/.gitconfig-work
> > credential.helper=cache
> > init.defaultbranch=main
> > core.repositoryformatversion=0
> > core.filemode=true
> > core.bare=false
> > core.logallrefupdates=true'''
> > ```
> 
> How do you get a case where `git config --list` will output blank lines? I've tried editing my git config files in various ways, but `git config --list` never has an empty line here. I also poked around at the code in config.c and builtin/config.c, particularly the show_all_config() and config_with_options() and nearby things, and I can't figure out from a brief look at the code how to get an empty line. So I'm not sure I believe the claim that line 1556 is equivalent to what you show here.
> 
> Could you explain how you get it? Or did you have other modifications that replaced the get_config_settings() function as well, but your replacement had blank lines?

I also ran into this issue. I have `[alis]` with `\n\n` in my `.gitconfig`.

```
[alias]
    co-commit = "!co_authored_commit(){ usage='usage: git commit -m \"Commit message\" --co \"co_author_name\"\n'; while [ \"${#}\" -gt 0 ]; do case \"${1}\" in -m) shift; message="${1}"; shift;; --co) shift; co_author=\"Co-authored-by: \"${1}\"\n\"; co_authors=\"${co_authors}${co_author}\"; shift;; *) shift;; esac; done; if [ -z \"${co_authors}\" ]; then echo ${usage}; exit 1; fi; if [ -z \"${message}\" ]; then echo ${usage}; exit 1; fi; co_authored_message=\"${message}\n\n\n${co_authors}\"; git commit -m \"${co_authored_message}\"; }; co_authored_commit"
```

It introduces new lines in `git config --list`:

```
alias.co-commit=!co_authored_commit(){ usage='usage: git commit -m "Commit message" --co "co_author_name"
'; while [ "${#}" -gt 0 ]; do case "${1}" in -m) shift; message=${1}; shift;; --co) shift; co_author="Co-authored-by: "${1}"
"; co_authors="${co_authors}${co_author}"; shift;; *) shift;; esac; done; if [ -z "${co_authors}" ]; then echo ${usage}; exit 1; fi; if [ -z "${message}" ]; then echo ${usage}; exit 1; fi; co_authored_message="${message}


${co_authors}"; git commit -m "${co_authored_message}"; }; co_authored_commit
```

Any suggestions?

**Comment by GavinMasterson** [comment]
As I said in my original post, I modified the Python code to enforce decoding in a UTF-8 locale. This allowed me to remove blank lines and prevent an error in the parsing of the config list.

**Comment by asvaza** [comment]
@GavinMasterson Thank you for fix. I run into new line issue and this helped me a lot. In my case regex for issue tracking integration uses new line character intentionally. It would be nice to have this fix included into codebase

.gitconfig
```
[bugtraq]
	url = https://redmine.company.com/issues/%BUGID%
	logregex = "[Rr]efs?:?(\\s*(,|and)?\\s*#\\d+)+\n(\\d+)"
```

**Comment by scosu** [comment]
I developed another mechanism to parse `git config list` that accepts multiline values. If someone could test if this solves the issue for them as well that would be great, will create a pull request later:

```
keyvalues = re.split(b'^([^=\n]+)=', output, flags=re.MULTILINE)
return {keyvalues[i].strip(): keyvalues[i + 1].strip() for i in range(1, len(keyvalues), 2)}
```

**Comment by Konfekt** [comment]
I also ran into this issue with somewhat involved aliases like

```
lf = "!f() { git log | tr -d '\n' | xsel --input --clipboard; }; f"
```

where `\n` seems to misinterpreted as a new line by the sanity check and throw an error about a missing `=` in the `git config --list` output.  That's indeed what `git config --list | grep -E '^[^=]+$'` shows

**Comment by Konfekt** [comment]
[These aliases](https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/16754068#16754068) may serve a test case for the robustness of the `=` check.
