### ISSUE TITLE
Avoid creating link to Azure DevOps work items

### ISSUE THREAD

**Issue by bh-sijtnic** [newren/git-filter-repo#608]
I am in the need to split multiple folders out of our big repository into a new repository.
I was able to use your script to do a test migration and successfully moved multiple folders.

In short, i ran these commands:

```
git clone http://AzureDevOpsServer:8080/Collection/Project/_git/Repo --single-branch
git filter-repo --analyze
git filter-repo --paths-from-file "C:\temp\folderstomove.txt"
git log --pretty=oneline --abbrev-commit
git remote add origin http://AzureDevOpsServer:8080/Collection/Project/_git/NewRepo
git push -u origin featureBranch
```
![image](https://github.com/user-attachments/assets/1fdc8c99-7eee-4e8d-aa7a-8dde731427c2)

After pushing, Azure DevOps generated thousands of emails for many users, work item updated emails saying a new commit was linked to the work item.
For this purpose, i dont need work items to be linked to the same commitId in another repository, the history will still be in the old repository i suppose. 

Is there a way to prevent Azure DevOps from linking the work item to the migrated commits? 

Also, what is your recommendation when moving code to another repository, simply "delete" the source folders? or do you have a better advise?

**Comment by newren** [comment]
> After pushing, Azure DevOps generated thousands of emails for many users, work item updated emails saying a new commit was linked to the work item.
For this purpose, i dont need work items to be linked to the same commitId in another repository, the history will still be in the old repository i suppose.

> Is there a way to prevent Azure DevOps from linking the work item to the migrated commits?

These sound like questions for Azure DevOps.  My code has nothing to do with generating emails, or linking commits to workitems, so I don't see how I could possibly affect any of that.  You'll need to contact the Azure DevOps folks to ask about why their services behave the way they do.

> Also, what is your recommendation when moving code to another repository, simply "delete" the source folders? or do you have a better advise?

If you move all the code elsewhere, you could delete the original repository (or archive it).  If you only moved some of it out, then deleting the source folders often works.  I've seen teams add comments to README.md files or similar to help people who wonder where certain sub-projects went, but that kind of thing is very specific to the workflows of individual projects.

**Comment by bh-sijtnic** [comment]
You are right, i found the right setting for this use case. Not sure if there is a way to avoid this using the tool, but in case anyone runs into it. in Azure DevOps you can disable the following settings under Repository settings

![image](https://github.com/user-attachments/assets/0c92d650-1c6d-4abb-aaef-20b61de88e6f)

After doing this i no longer receive the links and automated emails.
