### ISSUE TITLE
Errors out when encountering file type (i.e. regular file, symlink, submodule, ...) changes

### ISSUE THREAD

**Issue by sielicki** [newren/git-filter-repo#61]
Consider the following test script

```sh
#!/bin/sh

mkdir test_repo
cd test_repo/
ls
git init .
head -n 99 /usr/share/dict/words > some_words
git add some_words 
git commit -m "some words"
mv some_words new_words
ln -sf new_words some_words
git add .
git commit -m "a whole new world"
git diff-tree -r HEAD~1 HEAD
```

The output from the second commit is:

```
[master 582e472] a whole new world
 2 files changed, 1 insertion(+), 99 deletions(-)
 copy some_words => new_words (100%)
 rewrite some_words (100%)
 mode change 100644 => 120000
```

And the diff-tree output is:

```
:000000 100644 0000000000000000000000000000000000000000 b16a627c0c5f7b1159d2de646c556c6404aa17a0 A      new_words
:100644 120000 b16a627c0c5f7b1159d2de646c556c6404aa17a0 a2de965a04b037d5c187b1773875e62950015f21 T      some_words
```

This T scenario (manpage calls it a *T*ype change, "have their type (i.e. regular file, symlink, submodule, ...) changed (T)") is unhandled and results in a crash.

Willing to work on a patch if requested.

**Comment by sielicki** [comment]
Shoot. I just realized that this example script doesn't actually crash git-filter-repo. I guess that `get_file_changes` was not called in any of the contexts I tried. I do have a real-world repository where I'm encountering this, though, and clearly the T case isn't handled here (or in the FileChange class):

```python
  @staticmethod
  def get_file_changes(repo, parent_hash, commit_hash):
    """
    Return a FileChanges list with the differences between parent_hash
    and commit_hash
    """
    file_changes = []

    cmd = ["git", "diff-tree", "-r", parent_hash, commit_hash]
    output = subproc.check_output(cmd, cwd=repo)
    for line in output.splitlines():
      fileinfo, path = line.split(b'\t', 1)
      if path.startswith(b'"'):
        path = PathQuoting.dequote(path)
      oldmode, mode, oldhash, newhash, changetype = fileinfo.split()
      if changetype == b'D':
        file_changes.append(FileChange(b'D', path))
      elif changetype in (b'A', b'M'):
        identifier = HASH_TO_ID.get(newhash, newhash)
        file_changes.append(FileChange(b'M', path, identifier, mode))
      else: # pragma: no cover
        raise SystemExit("Unknown change type for line {}".format(line))

    return file_changes
```

**Comment by newren** [comment]
> Willing to work on a patch if requested.

That would be great!

**Comment by newren** [comment]
I just pushed commit e11343e5 (filter-repo: handle typechange modifications when first parent is pruned, 2020-03-23) to fix this, complete with a testcase...I wanted to get the change included in v2.26.0.  :-)

**Comment by sielicki** [comment]
Sorry for not being responsive. Thanks for the fix!

**Comment by newren** [comment]
No worries; life gets busy sometimes.  If you find another issue or want to contribute in another area, please do feel free.
