### ISSUE TITLE
Test fails with zlibng (t9394-filter-repo-sanity-checks-and-bigger-repo-setup.sh)

### ISSUE THREAD

**Issue by sebastianas** [newren/git-filter-repo#614]
I've seen that the main branch has some zlib-ng fixes. Unfortunately it does not work me.
It starts with the size detection which goes wrong. The test string hashes to e80fdf8cd5fb645649c14f41656a076dedc4e12a, too, but the size is reported as 77. This makes zlibng=-5. Based on test, the expected result would be 70.

The next failure is at
`  Total packed size (bytes): $((387+${zlibng}))`

With the size addition this goes to 382 but the files reads as 
`   Total packed size (bytes): 399 `

So the difference isn't constant. However, in blob-shas-and-paths.txt I have
`   a89c82a2d4b713a125a4323d25adda062cc0013d         44         60 numbers/medium.num`
so that is 12 again.

This is true for the remaining checks. I get the test passed if I skip the zlibng detection and hardcode it to 12.
Could we maybe relax the compressed size part? I haven't tested this on anything besides amd64 (zlib-ng_2.2.2) and I am not sure if the results are consistent there but it already appears to be different what you got.

**Comment by newren** [comment]
Yuck, what a pain.

> Could we maybe relax the compressed size part?

Yeah, we'll probably have to do something like that.

Since this only affects the tests and not the functioning of the code, it might be a while before I get to it...

**Comment by sebastianas** [comment]
On 2024-11-29 16:37:08 [-0800], Elijah Newren wrote:
> Yeah, we'll probably have to do something like that.
> 
> Since this only affects the tests and not the functioning of the code,
> it might be a while before I get to it...

I prepared something in case you want to roll with it.

Sebastian
