### ISSUE TITLE
[Feature Request] Is it possible to auto purge all deleted paths?

### ISSUE THREAD

**Issue by allenhsu** [newren/git-filter-repo#63]
We are creating a new repo from a sub directory of existing repo. We also want to cleanup history of deleted objects to make the repo further smaller. The output of --analyze is very helpful. I'm wondering if it's possible to have a flag to auto purge all deleted paths?

**Comment by newren** [comment]
filter-repo auto purges all deleted things by default.  Did you find a bug or some kind of case where that didn't happen?

**Comment by newren** [comment]
I'll assume you were just unaware this is the default and close this out; let me know if that's not the case or you still have a question or issue here.

**Comment by llamasoft** [comment]
I'm glad I came digging through the closed section of the issue tracker.  
This is exactly what I was looking for, but I couldn't find anywhere in the help or documentation that actually stated this.  In short, I was looking for something along the lines of "if the file is deleted from the current branch, purge it from history in all branches" (i.e. "empty the recycling bin"), but that appears to be the default operation.  Is my assessment of that correct?

**Comment by newren** [comment]
@llamasoft: Are you asking for a feature where any file that used to exist in the repository in other revisions (or branches) but does not exist in the current branch anymore be deleted from all revisions and branches and tags?  (Or, said another way, asking for git-filter-repo to discover which files look like they might have been deleted manually at some point and then automatically delete them everywhere?)  Or are you asking a question similar to the original reporter of whether a command like `git filter-repo --path README.md --invert-paths` will remove README.md from all branches/tags/etc.?

If the latter, it's in the first two sentences of the manual: "Rapidly rewrite entire repository history using user-specified filters. This is a destructive operation which should not be used lightly; it writes new commits, trees, tags, and blobs corresponding to (but filtered from) the original objects in the repository, then deletes the original history and leaves only the new."

**Comment by llamasoft** [comment]
I'm looking for the first option.  In essence, any file in `path-deleted-sizes.txt` when running with the `--analyze` flag be purged from the repo's history.

**Comment by newren** [comment]
@llamasoft: Okay, sounds like you are asking for something unrelated to the original issue.  Anyway, take the paths from `path-deleted-sizes.txt` and stick them in a file, then run `git filter-repo --invert-paths --paths-from-file DELETED_FILENAMES.TXT` and watch them all disappear.
