### ISSUE TITLE
lint-history: empty commits are removed or not depending on '--filenames-important' flag

### ISSUE THREAD

**Issue by thorbenk** [newren/git-filter-repo#64]
I'm running the `lint-history` script with the external `dos2unix` command to normalize line ending across my repository history (I'm on 46549e7d3f1e9369e5f77976c3e846205cdac4bd)

I've noticed the following strange behavior:
- If empty commits are created due to filtering, these empty commits
  - are **removed** if `--filenames-important` *is not present*
  - are **kept** if `--filenames-important` is given

Below is a script which creates a small repository with 6 linear commits, some of which only differ in line endings to the parent.  
I run `lint-history` with or without the `--filenames-important` flag, and then count the numbers of commits in the rewritten repo: They are 4 and 6.

```bash
#!/bin/bash

TMP="/tmp/bugreport_remove_empty"

REPO_ORIG=$TMP/repo_orig
REPO_LINT1=$TMP/repo_lint1
REPO_LINT2=$TMP/repo_lint2

# point this to a git checkout of the `git-filter-repo` repository
GIT_FILTER_REPO_DIR=/w/src/git-conversion/3rdparty/git-filter-repo

rm -rf $TMP
mkdir -p $REPO_ORIG
cd $REPO_ORIG
git init .
printf "windows\r\nline\r\nendings\r\n" > windows.txt
printf "int main()\n{\n  return 0;\n}\n" > a.cpp
printf "//header\nint foo();\nint bar();\n" > a.h
printf "int main() { return 0; }" > main.cpp
git add a.cpp a.h windows.txt main.cpp
git commit -am "[1] a.cpp with unix line endings"
unix2dos a.cpp
git commit -am "[2] a.cpp with windows line endings"
printf "line 4\nline 5\nline 6\n" >> a.cpp
git commit -am "[3] add three lines to a.cpp with unix line endings (now file has mixed endings)"
dos2unix a.cpp
git commit -am "[4] a.cpp rewritten with unix line endings"
printf "line 7\nline 8" >> a.cpp
git commit -am "[5] add two lines with unix line endings to a.cpp"
git rm a.cpp
git commit -am "[6] delete a.cpp"

cp -r $REPO_ORIG $REPO_LINT1
cp -r $REPO_ORIG $REPO_LINT2

cd $REPO_LINT1
export PYTHONPATH="$PWD"
ln -sf $GIT_FILTER_REPO_DIR/git-filter-repo git_filter_repo.py
$GIT_FILTER_REPO_DIR/contrib/filter-repo-demos/lint-history dos2unix

cd $REPO_LINT2
export PYTHONPATH="$PWD"
ln -sf $GIT_FILTER_REPO_DIR/git-filter-repo git_filter_repo.py
$GIT_FILTER_REPO_DIR/contrib/filter-repo-demos/lint-history --filenames-important dos2unix

cd $REPO_LINT1 && git rev-list HEAD | wc -l
cd $REPO_LINT2 && git rev-list HEAD | wc -l
```

**Comment by newren** [comment]
Yeah, I can reproduce with your script.  Thanks for the testcase.  Looks like blob_callback doesn't work well with the pruning of commits which become empty while the commit_callback does.

**Comment by newren** [comment]
I just pushed commit 4f84a74a (filter-repo: use more expensive prunability checks when needed, 2020-03-23) to fix this.
