### ISSUE TITLE
git-filter-repo --analyze --refs start..HEAD throws execption

### ISSUE THREAD

**Issue by domo141** [newren/git-filter-repo#65]
something like

    $ git-filter-repo --analyze --refs c7eee3fbe5ad8d075c9f2a1a9f390b73b6152849..HEAD

throws:

    Processed 369543 blob sizes
    Traceback (most recent call last):
       File "/home/user/bin/git-filter-repo", line 3888, in <module>
        RepoAnalyze.run(args)
      File "/home/user/bin/git-filter-repo", line 2623, in run
        stats = RepoAnalyze.gather_data(args)
      File "/home/user/bin/git-filter-repo", line 2344, in gather_data
        file_changes)
      File "/home/user/bin/git-filter-repo", line 2253, in analyze_commit
        graph.add_commit_and_parents(commit, parents)
      File "/home/user/bin/git-filter-repo", line 232, in add_commit_and_parents
        assert all(p in self.value for p in parents)
    AssertionError

This is inconvenient, thus

    $ git-filter-repo --dry-run --refs c7eee3fbe5ad8d075c9f2a1a9f390b73b6152849..HEAD

works fine.

It would be nicer to analyze the part one is interested -- without do to more filtering of one's own...

    $ git-filter-repo --version
    685886533097

(last change in commit b9c625 2020-02-10)

**Comment by newren** [comment]
Thanks for the clear report, I just pushed up a fix for this in commit fe33fc42 (filter-repo: avoid dying with --analyze on commits with unseen parents, 2020-03-21)

**Comment by domo141** [comment]
Thanks for fast fix. Works "perfectly". i.e. could verify my results by re-running analyze after changes...
