### ISSUE TITLE
"File renaming caused colliding pathnames!" shown when I don't think it should be

### ISSUE THREAD

**Issue by ptarjan** [newren/git-filter-repo#68]
First of all, thanks for the great tool!

I'm using it to construct a monorepo, by taking all of our other repos and moving them to be in `repo/` dirs and then octopus merging them into the monorepo. This works for most of our repos but fails if there is both a `README.md` and a `repo/README.md` file at some point in the history. I would expect them to just end up as `repo/README.md` and `repo/repo/README.md` respectively. Is there a way to do that?

I sometimes have a commit introducing them both (e.g. `package.json`), and sometimes a commit where one existed beforehand and we're just adding the new one (e.g. `Makefile`). Django repos are particularly susceptible to this since they like to have a top-level subdirectory named the same as the repo.

I'm using the command:
```
git filter-repo --to-subdirectory-filter repo
```

```
$ brew info git-filter-repo
git-filter-repo: stable 2.25.0
```

**Comment by newren** [comment]
This smells to me like it's the same problem fixed by commit b9c62540 (filter-repo: fix cache of file renames, 2020-02-10).  Could you try upgrading to v2.26.0?  It was released about half an hour before you filed this ticket, so brew probably hasn't picked it up yet...

**Comment by newren** [comment]
See also #53

**Comment by ptarjan** [comment]
Amazing! It did indeed fix the problem, thank you. \o/
