### ISSUE TITLE
Moving Subdirectory to Repository Root While Only Keeping Subdirectory History

### ISSUE THREAD

**Issue by tuzhucheng** [newren/git-filter-repo#70]
Hi, I'm wondering if it is possible to use `git-filter-repo` to extract the history of a single directory and have this single directory become the **root** of a repository.

Using `git filter-branch`, I can do this to achieve the desired effect:

```bash
git filter-branch --subdirectory-filter a/b/ -- --all
```

Using `git-filter-repo`, I'm trying to do something like this:

```bash
git filter-repo --path a/b/ --to-subdirectory-filter .
```

but using `.` is disallowed where `.` is the root of the repository. Is it possible to move the directory to the root?

**Comment by newren** [comment]
Yes, just do this:

`git filter-repo --subdirectory-filter a/b/`

Looks really similar to the filter-branch command line, but you don't need the annoying `-- --all` pieces.

**Comment by tuzhucheng** [comment]
Perfect, thank you for the prompt reply. This project is also really well done!
