### ISSUE TITLE
The --help cli command has outdated links

### ISSUE THREAD

**Issue by Radioreve** [newren/git-filter-repo#72]
Hello,

Great tool. `git-filter-repo --help ` outputs : 

```
For more detailed examples and explanations AND caveats, see
      https://github.com/newren/git-filter-repo#callbacks
```
Probably better use this one instead : 
https://github.com/newren/git-filter-repo/blob/master/Documentation/git-filter-repo.txt

**Comment by newren** [comment]
Or the html-ified version: https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS

Thanks for reporting, I'll fix this up shortly.

**Comment by newren** [comment]
Fixed now.  Thanks for the report!
