### ISSUE TITLE
Cannot process files that have names beginning with a dot

### ISSUE THREAD

**Issue by leni8ec** [newren/git-filter-repo#75]
This command can not be performed:
`git filter-repo --path-rename Assets/.gitattributes:.gitattributes`

I tried to specify the files in quotation marks `` ` `` or `"`, but this had no effect.
The problem was solved only using the same command, but through the file: 
`git filter-repo --paths-from-file ..\file_name.txt`

>  Git 2.26.0.windows.1, Windows 10, PowerShell 7

```
PS D:\Project> git filter-repo --path-rename Assets/.gitattributes:.gitattributes
Traceback (most recent call last):
  File "C:\Scoop\apps\git-filter-repo\2.26.0\git-filter-repo", line 3908, in <module>
    args = FilteringOptions.parse_args(sys.argv[1:])
  File "C:\Scoop\apps\git-filter-repo\2.26.0\git-filter-repo", line 2160, in parse_args
    args = parser.parse_args(input_args)
  File "C:\Scoop\apps\python\current\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Scoop\apps\python\current\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Scoop\apps\python\current\lib\argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Scoop\apps\python\current\lib\argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "C:\Scoop\apps\python\current\lib\argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Scoop\apps\git-filter-repo\2.26.0\git-filter-repo", line 1630, in __call__
    if values[0] and values[1] and not (
IndexError: list index out of range
.gitattributes : The term '.gitattributes' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
 name, or if a path was included, verify that the path is correct and try again.
At line:1 char:95
+ ... it-filter-repo.ps1 --path-rename Assets\.gitattributes;.gitattributes
+                                                            ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.gitattributes:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by newren** [comment]
```
At line:1 char:95
+ ... it-filter-repo.ps1 --path-rename Assets\.gitattributes;.gitattributes
+                                                            ~~~~~~~~~~~~~~
```

I see here that the error message uses a semicolon rather than a colon.  Does this mean you actually mis-typed the command and used the wrong character here, or does it mean that PowerShell is screwy in yet another way and that it unhelpfully transliterated the colon into a semicolon for you?  (If so, this seems like it'd be at least the third way that PowerShell screws things up for users; see https://github.com/newren/git-filter-repo/issues/36 and https://github.com/newren/git-filter-repo/issues/56)

**Comment by newren** [comment]
No response; I'll assume you just typoed the ':' into a ';' based on the error message and close this out.  Let me know if that's a bad assumption and you have any more information.

**Comment by newren** [comment]
And what happens if you run
```
$ echo git filter-repo --path-rename .github/workflows/stable-windows-man-arch.yml:.github/workflows/stable-windows-manual.yml
```
?  Note that I have put an `echo` at the front of the command, which means it'll run a different command that will simply print out what was passed to it.

**Comment by newren** [comment]
Wow, so you clearly have a single colon in the line you typed, and echo doesn't munge it, but filter-repo clearly doesn't see a colon.  What happens if you change your command from
```
git filter-repo --path-rename .github/workflows/stable-windows-man-arch.yml:.github/workflows/stable-windows-manual.yml
```
to
```
python3 git-filter-repo --path-rename .github/workflows/stable-windows-man-arch.yml:.github/workflows/stable-windows-manual.yml
```
?  Do you still get the `--path-rename expects one colon in its argument` error?
