### ISSUE TITLE
Question: Remove by glob but keep latest version in each branch.

### ISSUE THREAD

**Issue by alphaleonis** [newren/git-filter-repo#82]
I need to filter a repo by paths, to remove for example all old versions of `src/*.dll`, but I want to keep the latest committed version of the files in each branch.  I can't quite figure out how to do this. Is it possible to do with filter-repo?

**Comment by alphaleonis** [comment]
I think I may have been able to solve this by first learning some python, and then "stealing" some code from bfg-ish, most notably the `revert_tree_changes`, and creating my own commit_update that did filtering by globs in the way I wanted. 

So in short I do a normal filter-repo with a custom commit_update method, and then call `revert_tree_changes` with the branches I want to keep "untouched".  I honestly do not have much of an idea of what `revert_tree_changes` does or if this is the correct approach, but at first glance everything seems to be correct in the repo afterwards. (The files I wanted deleted were deleted, and it seems the files still remain in the branch tips that I wanted).

**Comment by newren** [comment]
Yup, bfg-ish had code to do this; you could even run bfg-ish directly if you wanted.  Anyway, glad you figured it out.
