### ISSUE TITLE
How do I replace a word in the entire history of commit messages?

### ISSUE THREAD

**Issue by acburigo** [newren/git-filter-repo#83]
Let's say I have commit history like

```
*  b50f96f Doing stuff D
*  2131692 Doing stuff C
*  b72fbf6 Doing stuff B
*  29a0ff0 Doing stuff A
```

and I want to replace the word _stuff_ by the word _task_, so that my history ends up looking like

```
*  b50f96f Doing task D
*  2131692 Doing task C
*  b72fbf6 Doing task B
*  29a0ff0 Doing task A
```

Is it possible to do that using this tool? If so, can someone help me with an example?

**Comment by newren** [comment]
I think the following should do it:
```
git-filter-repo --message-callback 'return message.replace(b"stuff", b"task")'
```

**Comment by acburigo** [comment]
It works, thanks! I just had to replace `'` by `"` and vice versa on Windows for it to work.

One thing to be aware of is that the commit hashes change after the operation.

**Comment by acburigo** [comment]
Is it possible to make this affect all branches?

**Comment by newren** [comment]
It affects all branches by default; you have to do extra work to make it only change one branch.

And yes, of course it changes all the commit hashes.  commit hashes in git are generated by hashing file contents, trees, author & committer names and dates, and the commit message.  If you change anything at all using filter-repo (or any other tool), you get new commit ids.
