### ISSUE TITLE
Installation from pip does not work under Git for Windows bash if invoked as git-filter-repo

### ISSUE THREAD

**Issue by qm2k** [newren/git-filter-repo#87]
On my system the first line of the installed script (`C:\Program Files\Python37\Scripts\git-filter-repo`) looked like this:
```
#!c:\program files\python37\python.exe
```
At least in Git for Windows it fails to work:
```
$ git-filter-repo
bash: /c/Program Files/Python37/Scripts/git-filter-repo: c:\program: bad interpreter: No such file or directory     
```
Actually, it sholdn't work anywhere.

I could not find the code but experiments shown that the path of pip interpreter is being used. I think it is incorrect since on most systems it will led to the wrong result.

Perosnally, I think it would better be left as `#!/usr/bin/env python3` even on Windows. It is true that python3 is absent in the standard Python for Windows installation, but this is a problem of Python, not git-filter-repo, it is common to many scripts, and it has a simple solution (create a copy of python.exe as python3.exe). I hope Python for Windows will fix it some day in their distribution.

Alternatively, [ctypes.windll.kernel32.GetShortPathNameW](https://stackoverflow.com/a/23598461) can be used to convert long version of the interpreter path to a shorter version without spaces. 

One might say that I should simply invoke it as `git filter-repo`, not `git-filter-repo`. Unfortunately, under Git for Windows only `git-filter-repo --help` works, the former version produces the following error:
```
$ git filter-repo --help
The system cannot find the file C:/Program Files/Git/mingw64/share/doc/git-doc/git-filter-repo.html.
```
I don't know if these two are related, or the missing `git-filter-repo.html` is a separate problem.

**Comment by newren** [comment]
The hashbang line is something that is handled by pip, not by me, according to https://github.com/newren/git-filter-repo/issues/11#issuecomment-553159083.  Certainly, I don't have any code for defining what goes there, I just have "#!/usr/bin/env python3" hard-coded and mention in my installation notes that it's up to people and packagers to change it if needed.

As for manual pages, I'm not sure pip would even have access to install them in the needed places, and would vary heavily from Windows to Mac OS X to Linux.  (Windows would use the .html files, Linux would probably use the manpage, and who knows what's best on the Mac.)  I'm not sure it'd even make sense to attempt to put that logic into the pip packages, and if pip would even have access.  Native system packagers might be the better route to go.

Speaking of native system packages, perhaps you could install git-filter-repo using scoop and have all these issues solved for you?

**Comment by qm2k** [comment]
Oops, I seem to be complaining to the wrong person. Ok, well try to bring it to the PyPI people then. 
As for me, I fixed the first line manually and your program worked great (thank you, BTW, it saved me a ton of time). I was just surprised it didn't start out of the box. I also learned (once again) to put short version of Python directory (C:\Progra~1...) in PATH.
