### ISSUE TITLE
Add a "--preserve-formatting" option

### ISSUE THREAD

**Issue by Mumeii** [newren/git-filter-repo#89]
Hi

I've been using git-filter-repo in order to strip a repository from its secrets.

The repository is quite big and, as it's a sensitive subject, I first wanted to perform a `--dry-run` in order to compare both the `.original` and `.filtered` files produced by the following command :
 
```
git filter-repo --dry-run --replace-text ./myObfuscationScript.txt
```

Doing so I've noticed that the following lines of code in git-filter-repo don't ease at all the comparison : 

https://github.com/newren/git-filter-repo/blob/c0c37a7656404dcefff55e55b8f7a9662f9d959d/git-filter-repo#L692-L696

As mentioned by the comment, this cometic choice make the reading of the `.filtered` file easier ... but ruine the user experience that use comparison tools on produced files. 

Especially for big code base (>250Mo) containing binary blobs : only diff commands can compare such consequent files efficiently. But it quickly get a mess if they are many extra `\n` here and there.

So, would it be possible to include an option that, at least for the sake of comparing files produced by a `--dry-run`, would have `.filtered` formatting been as close to `.original` as possible ?

For the same reasons I wonder if it's absolutely necessary to strip the `.filtered` resulting file from the `original-oid ...` lines ? 

Would it prevent the non `--dry-run`, fast-import, processing still including them ?

And after removal of the extra `\n` causing troubles for comparison, I've also spotted the following kinds of discrepancies that could be interesting candidates been influenced by this requested option :  

file manipulation reordering : 
=====================
```
M 100644 :9272 sql/16.09/PROJECTNAME__16.09.1__SE-392_belgium_deee.sql
D sql/16.09/PROJECTNAME__16.09.1__SE-392_belgium_deee
M 100644 :9276 sql/16.09/PROJECTNAME__16.09.2__SE-386_TN_Qrcode.sql
D sql/16.09/PROJECTNAME__16.09.2__SE-386_TN_Qrcode
```
been turned into
```
D sql/16.09/PROJECTNAME__16.09.1__SE-392_belgium_deee
M 100644 :9272 sql/16.09/PROJECTNAME__16.09.1__SE-392_belgium_deee.sql
D sql/16.09/PROJECTNAME__16.09.2__SE-386_TN_Qrcode
M 100644 :9276 sql/16.09/PROJECTNAME__16.09.2__SE-386_TN_Qrcode.sql
```

file manipulation reordering : 
=====================
```
from :18496
M 100644 :18495 sql/PROJECTNAME__802.0__correct_be_qrcode.sql
D sql/PROJECTNAME__802.0__correct_be_qrcode
```
been turned into
```
from :18496
D sql/PROJECTNAME__802.0__correct_be_qrcode
M 100644 :18495 sql/PROJECTNAME__802.0__correct_be_qrcode.sql
```

file name re-encoding :
=================
````
D "components/src/main/resources/img/pt/pt_PRIXTECH_DSM_A4 .png"
````
been turned into
````
D components/src/main/resources/img/pt/pt_PRIXTECH_DSM_A4 .png
````

**Comment by newren** [comment]
Sorry, but this would be extraordinarily difficult to implement, maybe even impossible once you consider that people can rename files or add or remove them from the stream, add new commits not found in the original, remove commits, etc.  Also, filter-repo isn't part of git-core currently, meaning I have to work with multiple versions of fast-export, and if one comes along and changes the order slightly, then I'd have to find out which version of git the user is running and have code to output both formats.

In constrast, you can just make two clones, run filter-repo on one of them, and then compare the two using any of:
  1) Run `git fast-export --all` from both directories, then compare the output
  2) fetch one into the other (e.g. `git fetch ../FILTERED_CLONE +refs/heads/*:refs/remotes/filtered/*`) and do some branch tip or branch range comparisons, e.g.:
    * `git range-diff master...filtered/master`
    * `git diff master filtered/master`

Hope that helps; let me know if any of it is unclear.  I'll close out since the original request isn't something I'm willing to attempt to implement.

**Comment by Mumeii** [comment]
Hi @newren !

Well, I partly understand the workaround you advise, and I'll maybe give it a try if I find time for it. But no matter if it fits my need or not, I still feel like the `--dry-run` option is not as good as it could be :

Thanks your workaround advise I thought of another way to do what I'm looking for, but I still have to test it : 

1) Produce two clones of my repo : 
* A first one that will serve as a reference
* A second one on which I'll apply my secrets obfuscations
2) Manipulate both the following way : 
* Apply a "blank" `git filter-repo --dry-run --replace-text ./myBlankObfuscationScript.txt` run on reference repo, with an empty replacement script `./myBlankObfuscationScript.txt`
* Apply a regular `git filter-repo --dry-run --replace-text ./myObfuscationScript.txt` on the other one
3) Finally compare the `.filtered` files from both reference and obfuscated clones

If it's a valid way to achieve what I'm looking for, that's quite many manipulations to perform myself whereas git-filter-repo is blitzing fast ⚡  and could do it itself 😋 !

In that case why not adding an extra option `--dry-run-with-blank-filtering` ?

This option would produce an extra `.blankFiltering` file in addition to the `.original` and `.filtered` ones. 

This could greatly help users focussing exclusively on the modifications they requested compared to the ones introduced by git-filter-repo itself

Looking forward for you point of view about it

**Comment by Mumeii** [comment]
I've been checking the method I've proposed and it's realy fitting my needs 💯%

So I confirm that been able to have this extra `.blankFiltering` file would be great for user having the same need 🥳  

Plus I guess it shouldn't be that complexe to simulate an extra dry & blank run to produce this file, or am I wrong ?

**Comment by newren** [comment]
There's a couple issues here:

* --dry-run, by it's nature, doesn't call fast-import to write the new data out -- but that means that the only thing that knows what the new commit IDs (fast-import) isn't executing and thus we can't know the new commit IDs.  Thus, for dry-runs, I have to turn off the automatic rewriting of commit IDs.  For similar but more complicated reasons, it also disables some cases of removing commits that become empty.  These changes might actually make it easier to compare results in some cases, particularly when the commit ID updating or empty commit pruning weren't the parts you were interested in, but if those things were among the parts you wanted to watch out for then this is just an approximation comparison tool that "lies" about the part you want to know about.

* The utility of this procedure seems to be somewhat titled towards rewriting rules that end up not adding or removing commits; when you are just modifying the contents of existing commits then your procedure provides a very easy way to compare.  But once you add or remove commits the diff between the outputs is going to start looking ugly and alternative choices like range-diff might be a better way to compare.

I can see that this case solves your needs quite well, but it's unfortunately not a general solution.
