### ISSUE TITLE
Example for keeping history of files from last commit only

### ISSUE THREAD

**Issue by mlesin** [newren/git-filter-repo#91]
Please provide an example for a way to keep history only for files from last commits for all branches (or at least selected one)
I see this case as pretty common for me but can't figure out clear syntax for that task using git-filter-repo

**Comment by newren** [comment]
Well, if you decided that the files you are currently tracking are the only ones that are relevant, and you only want to keep the history of those files on any branch/tag/whatever, you could run:

```
git ls-files >/tmp/current-files
git filter-repo --paths-from-file /tmp/current-files
```

If there were two branches that mattered to you, you could do something like

```
git ls-tree -r $BRANCH1 >../my-files
git ls-tree -r $BRANCH2 >>../my-files
sort ../my-files | uniq >../my-relevant-files
git filter-repo --paths-from-file ../my-relevant-files
```

Or you could use analyze to help you out:
```
git filter-repo --analyze
```
Then look through the created .git/filter-repo/analysis/*deleted* files, probably .git/filter-repo/analysis/path-deleted-sizes.txt.  Pick out all the files you want to nuke and stick just the filenames (not all the other stats) in some file, then run
```
git filter-repo --invert-paths --paths-from-file /PATH/TO/FILE-LISTING-UNWANTED-FILES
```

There's lots of ways to slice and dice this.  Hope that helps.

**Comment by mlesin** [comment]
Thanks, that explains a lot! It would be great to have such a good explanation in the documentation, by the way. That would cut such questions in half ;)
