### ISSUE TITLE
Question/More examples? How to change line endings CRLF -> LF for specific file extensions?

### ISSUE THREAD

**Issue by saas2813** [newren/git-filter-repo#99]
Hi

I have recently imported a repo from SVN.
I would like to ensure that all text files (Identified by given globs) have LF line-termination.
I would also appreciate being able to convert them to UTF-8 as needed.

From the docs I would guess it involves --filter-text or --blob-calback but I can not find how to limit them to specific filename-GLOBS.

Any help appreciated.

**Comment by newren** [comment]
You'll probably be interested in [the lint-history example](../blob/master/contrib/filter-repo-demos/lint-history), and also in the various posts on issue #45 where people have modified it to run various linters on just certain filetypes.

Does that help?

**Comment by newren** [comment]
In commit 23bec32283 (contrib, docs: make discovery of code formatting and linting easier, 2020-06-06) I made it even easier to run lint-historyon specific files from history, and added it as [an example in the conversion from filter-branch comparison](https://github.com/newren/git-filter-repo/blob/master/Documentation/converting-from-filter-branch.md#cheat-sheet-additional-conversion-examples).
